# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.stores_api import StoresApi


class TestStoresApi(unittest.TestCase):
    """StoresApi unit test stubs"""

    def setUp(self) -> None:
        self.api = StoresApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_data_stores_get(self) -> None:
        """Test case for api_v1_data_stores_get

        Get all data stores.
        """
        pass

    def test_api_v1_data_stores_id_get(self) -> None:
        """Test case for api_v1_data_stores_id_get

        Get a single data store by id.
        """
        pass


if __name__ == '__main__':
    unittest.main()
