# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.file_summary_dto import FileSummaryDTO

class TestFileSummaryDTO(unittest.TestCase):
    """FileSummaryDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileSummaryDTO:
        """Test FileSummaryDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileSummaryDTO`
        """
        model = FileSummaryDTO()
        if include_optional:
            return FileSummaryDTO(
                id = '',
                name = '',
                download_uri = '',
                content_type = openapi_client.models.content_type_dto.ContentTypeDTO(
                    id = '', 
                    abbreviation = '', 
                    display_name = '', 
                    description = '', 
                    mime_type = '', ),
                size = 56,
                created_stamp_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_stamp_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                begin_stamp_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_stamp_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                is_time_series = True,
                is_deleted = True
            )
        else:
            return FileSummaryDTO(
        )
        """

    def testFileSummaryDTO(self):
        """Test FileSummaryDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
