# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.data_set_summary_dto import DataSetSummaryDTO

class TestDataSetSummaryDTO(unittest.TestCase):
    """DataSetSummaryDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DataSetSummaryDTO:
        """Test DataSetSummaryDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DataSetSummaryDTO`
        """
        model = DataSetSummaryDTO()
        if include_optional:
            return DataSetSummaryDTO(
                id = '',
                slug = '',
                name = '',
                assigned_tags = [
                    openapi_client.models.tag_dto.TagDTO(
                        id = '', 
                        name = '', )
                    ],
                created_stamp_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                deleted_stamp_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                begin_stamp_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_stamp_utc = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                state = '',
                is_time_series = True,
                is_deleted = True,
                metadata_fields = [
                    ''
                    ],
                file_count = 56,
                collection_id = ''
            )
        else:
            return DataSetSummaryDTO(
        )
        """

    def testDataSetSummaryDTO(self):
        """Test DataSetSummaryDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
