# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.projects_api import ProjectsApi


class TestProjectsApi(unittest.TestCase):
    """ProjectsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ProjectsApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_projects_get(self) -> None:
        """Test case for api_v1_projects_get

        Get all projects.
        """
        pass

    def test_api_v1_projects_id_get(self) -> None:
        """Test case for api_v1_projects_id_get

        """
        pass

    def test_api_v1_projects_id_put(self) -> None:
        """Test case for api_v1_projects_id_put

        Id field on the body is ignored.
        """
        pass


if __name__ == '__main__':
    unittest.main()
