# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.content_type_dto import ContentTypeDTO

class TestContentTypeDTO(unittest.TestCase):
    """ContentTypeDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ContentTypeDTO:
        """Test ContentTypeDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ContentTypeDTO`
        """
        model = ContentTypeDTO()
        if include_optional:
            return ContentTypeDTO(
                id = '',
                abbreviation = '',
                display_name = '',
                description = '',
                mime_type = ''
            )
        else:
            return ContentTypeDTO(
        )
        """

    def testContentTypeDTO(self):
        """Test ContentTypeDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
