# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.file_create_response_dto import FileCreateResponseDTO

class TestFileCreateResponseDTO(unittest.TestCase):
    """FileCreateResponseDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> FileCreateResponseDTO:
        """Test FileCreateResponseDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `FileCreateResponseDTO`
        """
        model = FileCreateResponseDTO()
        if include_optional:
            return FileCreateResponseDTO(
                upload_uri = '',
                file_id = ''
            )
        else:
            return FileCreateResponseDTO(
        )
        """

    def testFileCreateResponseDTO(self):
        """Test FileCreateResponseDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
