# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.s3_file_create_request_dto import S3FileCreateRequestDTO

class TestS3FileCreateRequestDTO(unittest.TestCase):
    """S3FileCreateRequestDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> S3FileCreateRequestDTO:
        """Test S3FileCreateRequestDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `S3FileCreateRequestDTO`
        """
        model = S3FileCreateRequestDTO()
        if include_optional:
            return S3FileCreateRequestDTO(
                name = '',
                content_type_id = '',
                size_bytes = 56,
                plain_sha256_hash = '',
                created_stamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                begin_stamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                end_stamp = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                compression_algorithm = '',
                compressed_sha256_hash = '',
                compressed_size_bytes = 56
            )
        else:
            return S3FileCreateRequestDTO(
        )
        """

    def testS3FileCreateRequestDTO(self):
        """Test S3FileCreateRequestDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
