# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.collections_api import CollectionsApi


class TestCollectionsApi(unittest.TestCase):
    """CollectionsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CollectionsApi()

    def tearDown(self) -> None:
        pass

    def test_api_v1_data_collections_get(self) -> None:
        """Test case for api_v1_data_collections_get

        Get all collections.
        """
        pass

    def test_api_v1_data_collections_id_get(self) -> None:
        """Test case for api_v1_data_collections_id_get

        Get a single collection by id.
        """
        pass

    def test_api_v1_data_collections_post(self) -> None:
        """Test case for api_v1_data_collections_post

        Add a single item to the system.
        """
        pass


if __name__ == '__main__':
    unittest.main()
