# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.project_summary_dto import ProjectSummaryDTO

class TestProjectSummaryDTO(unittest.TestCase):
    """ProjectSummaryDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProjectSummaryDTO:
        """Test ProjectSummaryDTO
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProjectSummaryDTO`
        """
        model = ProjectSummaryDTO()
        if include_optional:
            return ProjectSummaryDTO(
                id = '',
                slug = '',
                name = '',
                description = '',
                collections = [
                    openapi_client.models.collection_summary_dto.CollectionSummaryDTO(
                        id = '', 
                        slug = '', 
                        name = '', 
                        description = '', 
                        data_set_count = 56, 
                        default_data_store_id = '', 
                        project_id = '', )
                    ],
                data_stores = [
                    openapi_client.models.data_store_summary_dto.DataStoreSummaryDTO(
                        id = '', 
                        slug = '', 
                        name = '', 
                        files_count = 56, 
                        storage_type = '', 
                        properties_json = '', 
                        project_id = '', )
                    ]
            )
        else:
            return ProjectSummaryDTO(
        )
        """

    def testProjectSummaryDTO(self):
        """Test ProjectSummaryDTO"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
