/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionDetailedDTO,
  CollectionSummaryDTO,
  ProblemDetails,
} from '../models/index';
import {
    CollectionDetailedDTOFromJSON,
    CollectionDetailedDTOToJSON,
    CollectionSummaryDTOFromJSON,
    CollectionSummaryDTOToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface ApiV1DataCollectionsGetRequest {
    projectId?: string;
    projectSlug?: string;
    slug?: string;
}

export interface ApiV1DataCollectionsIdGetRequest {
    id: string;
}

export interface ApiV1DataCollectionsIdMetadataKeyPutRequest {
    id: string;
    key: string;
    defaultMetadataId?: string;
    body?: string;
}

export interface ApiV1DataCollectionsPostRequest {
    collectionSummaryDTO?: CollectionSummaryDTO;
}

/**
 * 
 */
export class CollectionsApi extends runtime.BaseAPI {

    /**
     * Get all collections.
     */
    async apiV1DataCollectionsGetRaw(requestParameters: ApiV1DataCollectionsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<CollectionSummaryDTO>>> {
        const queryParameters: any = {};

        if (requestParameters['projectId'] != null) {
            queryParameters['projectId'] = requestParameters['projectId'];
        }

        if (requestParameters['projectSlug'] != null) {
            queryParameters['projectSlug'] = requestParameters['projectSlug'];
        }

        if (requestParameters['slug'] != null) {
            queryParameters['slug'] = requestParameters['slug'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/data/collections`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CollectionSummaryDTOFromJSON));
    }

    /**
     * Get all collections.
     */
    async apiV1DataCollectionsGet(requestParameters: ApiV1DataCollectionsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<CollectionSummaryDTO>> {
        const response = await this.apiV1DataCollectionsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get a single collection by id.
     */
    async apiV1DataCollectionsIdGetRaw(requestParameters: ApiV1DataCollectionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionDetailedDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1DataCollectionsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/data/collections/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionDetailedDTOFromJSON(jsonValue));
    }

    /**
     * Get a single collection by id.
     */
    async apiV1DataCollectionsIdGet(requestParameters: ApiV1DataCollectionsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionDetailedDTO> {
        const response = await this.apiV1DataCollectionsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1DataCollectionsIdMetadataKeyPutRaw(requestParameters: ApiV1DataCollectionsIdMetadataKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1DataCollectionsIdMetadataKeyPut().'
            );
        }

        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling apiV1DataCollectionsIdMetadataKeyPut().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['defaultMetadataId'] != null) {
            queryParameters['defaultMetadataId'] = requestParameters['defaultMetadataId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/data/collections/{id}/metadata/{key}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1DataCollectionsIdMetadataKeyPut(requestParameters: ApiV1DataCollectionsIdMetadataKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1DataCollectionsIdMetadataKeyPutRaw(requestParameters, initOverrides);
    }

    /**
     * Add a single item to the system.
     */
    async apiV1DataCollectionsPostRaw(requestParameters: ApiV1DataCollectionsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/api/v1/data/collections`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionSummaryDTOToJSON(requestParameters['collectionSummaryDTO']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add a single item to the system.
     */
    async apiV1DataCollectionsPost(requestParameters: ApiV1DataCollectionsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1DataCollectionsPostRaw(requestParameters, initOverrides);
    }

}
