/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  DataSetDetailedDTO,
  DataSetSummaryDTO,
  ErrorMessageDTO,
  FileCreateResponseDTO,
  ProblemDetails,
  S3FileCreateRequestDTO,
} from '../models/index';
import {
    DataSetDetailedDTOFromJSON,
    DataSetDetailedDTOToJSON,
    DataSetSummaryDTOFromJSON,
    DataSetSummaryDTOToJSON,
    ErrorMessageDTOFromJSON,
    ErrorMessageDTOToJSON,
    FileCreateResponseDTOFromJSON,
    FileCreateResponseDTOToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
    S3FileCreateRequestDTOFromJSON,
    S3FileCreateRequestDTOToJSON,
} from '../models/index';

export interface ApiV1DataDatasetsBatchPostRequest {
    dataSetSummaryDTO?: Array<DataSetSummaryDTO>;
}

export interface ApiV1DataDatasetsGetRequest {
    collectionId?: string;
    deleted?: string;
}

export interface ApiV1DataDatasetsIdAddS3PostRequest {
    id: string;
    s3FileCreateRequestDTO?: S3FileCreateRequestDTO;
}

export interface ApiV1DataDatasetsIdDeleteRequest {
    id: string;
}

export interface ApiV1DataDatasetsIdGetRequest {
    id: string;
}

export interface ApiV1DataDatasetsIdSealPutRequest {
    id: string;
}

export interface ApiV1DataDatasetsPostRequest {
    dataSetSummaryDTO?: DataSetSummaryDTO;
}

/**
 * 
 */
export class DataSetsApi extends runtime.BaseAPI {

    /**
     * Add a batch of item to the system.
     */
    async apiV1DataDatasetsBatchPostRaw(requestParameters: ApiV1DataDatasetsBatchPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/data/datasets/batch`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['dataSetSummaryDTO']!.map(DataSetSummaryDTOToJSON),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Add a batch of item to the system.
     */
    async apiV1DataDatasetsBatchPost(requestParameters: ApiV1DataDatasetsBatchPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1DataDatasetsBatchPostRaw(requestParameters, initOverrides);
    }

    /**
     * Get data sets.
     */
    async apiV1DataDatasetsGetRaw(requestParameters: ApiV1DataDatasetsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DataSetSummaryDTO>>> {
        const queryParameters: any = {};

        if (requestParameters['collectionId'] != null) {
            queryParameters['collectionId'] = requestParameters['collectionId'];
        }

        if (requestParameters['deleted'] != null) {
            queryParameters['deleted'] = requestParameters['deleted'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/data/datasets`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DataSetSummaryDTOFromJSON));
    }

    /**
     * Get data sets.
     */
    async apiV1DataDatasetsGet(requestParameters: ApiV1DataDatasetsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DataSetSummaryDTO>> {
        const response = await this.apiV1DataDatasetsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Add a single file to the system. Request a single S3 upload URL.
     */
    async apiV1DataDatasetsIdAddS3PostRaw(requestParameters: ApiV1DataDatasetsIdAddS3PostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileCreateResponseDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1DataDatasetsIdAddS3Post().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/data/datasets/{id}/add/s3`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: S3FileCreateRequestDTOToJSON(requestParameters['s3FileCreateRequestDTO']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileCreateResponseDTOFromJSON(jsonValue));
    }

    /**
     * Add a single file to the system. Request a single S3 upload URL.
     */
    async apiV1DataDatasetsIdAddS3Post(requestParameters: ApiV1DataDatasetsIdAddS3PostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileCreateResponseDTO> {
        const response = await this.apiV1DataDatasetsIdAddS3PostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async apiV1DataDatasetsIdDeleteRaw(requestParameters: ApiV1DataDatasetsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1DataDatasetsIdDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/data/datasets/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiV1DataDatasetsIdDelete(requestParameters: ApiV1DataDatasetsIdDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1DataDatasetsIdDeleteRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiV1DataDatasetsIdGetRaw(requestParameters: ApiV1DataDatasetsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<DataSetDetailedDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1DataDatasetsIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/data/datasets/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => DataSetDetailedDTOFromJSON(jsonValue));
    }

    /**
     */
    async apiV1DataDatasetsIdGet(requestParameters: ApiV1DataDatasetsIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<DataSetDetailedDTO> {
        const response = await this.apiV1DataDatasetsIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Seals a data set. Only works for data sets that are in \"Uninitialized\" state.
     */
    async apiV1DataDatasetsIdSealPutRaw(requestParameters: ApiV1DataDatasetsIdSealPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1DataDatasetsIdSealPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/data/datasets/{id}/seal`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id']))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Seals a data set. Only works for data sets that are in \"Uninitialized\" state.
     */
    async apiV1DataDatasetsIdSealPut(requestParameters: ApiV1DataDatasetsIdSealPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1DataDatasetsIdSealPutRaw(requestParameters, initOverrides);
    }

    /**
     * Add a single item to the system.
     */
    async apiV1DataDatasetsPostRaw(requestParameters: ApiV1DataDatasetsPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<string>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/v1/data/datasets`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: DataSetSummaryDTOToJSON(requestParameters['dataSetSummaryDTO']),
        }, initOverrides);

        if (this.isJsonMime(response.headers.get('content-type'))) {
            return new runtime.JSONApiResponse<string>(response);
        } else {
            return new runtime.TextApiResponse(response) as any;
        }
    }

    /**
     * Add a single item to the system.
     */
    async apiV1DataDatasetsPost(requestParameters: ApiV1DataDatasetsPostRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<string> {
        const response = await this.apiV1DataDatasetsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * OData enabled query.
     */
    async apiV1DataDatasetsQueryGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<DataSetSummaryDTO>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/v1/data/datasets/query`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(DataSetSummaryDTOFromJSON));
    }

    /**
     * OData enabled query.
     */
    async apiV1DataDatasetsQueryGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<DataSetSummaryDTO>> {
        const response = await this.apiV1DataDatasetsQueryGetRaw(initOverrides);
        return await response.value();
    }

}
