/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ApiV1DataFilesGet200ResponseInner,
  ErrorMessageDTO,
  FileDetailedDTO,
  FileListViewMode,
  MetaDateDTO,
  ProblemDetails,
} from '../models/index';
import {
    ApiV1DataFilesGet200ResponseInnerFromJSON,
    ApiV1DataFilesGet200ResponseInnerToJSON,
    ErrorMessageDTOFromJSON,
    ErrorMessageDTOToJSON,
    FileDetailedDTOFromJSON,
    FileDetailedDTOToJSON,
    FileListViewModeFromJSON,
    FileListViewModeToJSON,
    MetaDateDTOFromJSON,
    MetaDateDTOToJSON,
    ProblemDetailsFromJSON,
    ProblemDetailsToJSON,
} from '../models/index';

export interface ApiV1DataFileRefsGetRequest {
    storeGuid?: string;
    type?: string;
}

export interface ApiV1DataFilesGetRequest {
    view?: FileListViewMode;
}

export interface ApiV1DataFilesIdBlobGetRequest {
    id: string;
}

export interface ApiV1DataFilesIdContentGetRequest {
    id: string;
}

export interface ApiV1DataFilesIdGetRequest {
    id: string;
}

export interface ApiV1DataFilesIdMetadataKeyDeleteRequest {
    id: string;
    key: string;
}

export interface ApiV1DataFilesIdMetadataKeyPostRequest {
    id: string;
    key: string;
    newKey?: string;
}

export interface ApiV1DataFilesIdMetadataKeyPutRequest {
    id: string;
    key: string;
    body?: string;
}

/**
 * 
 */
export class FilesApi extends runtime.BaseAPI {

    /**
     */
    async apiV1DataFileRefsGetRaw(requestParameters: ApiV1DataFileRefsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ApiV1DataFilesGet200ResponseInner>> {
        const queryParameters: any = {};

        if (requestParameters['storeGuid'] != null) {
            queryParameters['storeGuid'] = requestParameters['storeGuid'];
        }

        if (requestParameters['type'] != null) {
            queryParameters['type'] = requestParameters['type'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/data/file-refs`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ApiV1DataFilesGet200ResponseInnerFromJSON(jsonValue));
    }

    /**
     */
    async apiV1DataFileRefsGet(requestParameters: ApiV1DataFileRefsGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ApiV1DataFilesGet200ResponseInner> {
        const response = await this.apiV1DataFileRefsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Get files.
     */
    async apiV1DataFilesGetRaw(requestParameters: ApiV1DataFilesGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<ApiV1DataFilesGet200ResponseInner>>> {
        const queryParameters: any = {};

        if (requestParameters['view'] != null) {
            queryParameters['view'] = requestParameters['view'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/data/files`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(ApiV1DataFilesGet200ResponseInnerFromJSON));
    }

    /**
     * Get files.
     */
    async apiV1DataFilesGet(requestParameters: ApiV1DataFilesGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<ApiV1DataFilesGet200ResponseInner>> {
        const response = await this.apiV1DataFilesGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Request a download of a file. Not all files are available for download. On success, the raw bytes will be returned.
     */
    async apiV1DataFilesIdBlobGetRaw(requestParameters: ApiV1DataFilesIdBlobGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Blob>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1DataFilesIdBlobGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/data/files/{id}/blob`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.BlobApiResponse(response);
    }

    /**
     * Request a download of a file. Not all files are available for download. On success, the raw bytes will be returned.
     */
    async apiV1DataFilesIdBlobGet(requestParameters: ApiV1DataFilesIdBlobGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Blob> {
        const response = await this.apiV1DataFilesIdBlobGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Request redirect to a file. On success, a 302 referring to the final download URL will be returned.
     */
    async apiV1DataFilesIdContentGetRaw(requestParameters: ApiV1DataFilesIdContentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1DataFilesIdContentGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/data/files/{id}/content`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Request redirect to a file. On success, a 302 referring to the final download URL will be returned.
     */
    async apiV1DataFilesIdContentGet(requestParameters: ApiV1DataFilesIdContentGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1DataFilesIdContentGetRaw(requestParameters, initOverrides);
    }

    /**
     * Get details of a single file.
     */
    async apiV1DataFilesIdGetRaw(requestParameters: ApiV1DataFilesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<FileDetailedDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1DataFilesIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/data/files/{id}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => FileDetailedDTOFromJSON(jsonValue));
    }

    /**
     * Get details of a single file.
     */
    async apiV1DataFilesIdGet(requestParameters: ApiV1DataFilesIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<FileDetailedDTO> {
        const response = await this.apiV1DataFilesIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Removes metadate relation with resp. key.
     */
    async apiV1DataFilesIdMetadataKeyDeleteRaw(requestParameters: ApiV1DataFilesIdMetadataKeyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1DataFilesIdMetadataKeyDelete().'
            );
        }

        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling apiV1DataFilesIdMetadataKeyDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/data/files/{id}/metadata/{key}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        const response = await this.request({
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Removes metadate relation with resp. key.
     */
    async apiV1DataFilesIdMetadataKeyDelete(requestParameters: ApiV1DataFilesIdMetadataKeyDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1DataFilesIdMetadataKeyDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Rename key for metadate relation.
     */
    async apiV1DataFilesIdMetadataKeyPostRaw(requestParameters: ApiV1DataFilesIdMetadataKeyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1DataFilesIdMetadataKeyPost().'
            );
        }

        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling apiV1DataFilesIdMetadataKeyPost().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['newKey'] != null) {
            queryParameters['newKey'] = requestParameters['newKey'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/api/v1/data/files/{id}/metadata/{key}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Rename key for metadate relation.
     */
    async apiV1DataFilesIdMetadataKeyPost(requestParameters: ApiV1DataFilesIdMetadataKeyPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiV1DataFilesIdMetadataKeyPostRaw(requestParameters, initOverrides);
    }

    /**
     * Adds or sets meta documents for a file.
     */
    async apiV1DataFilesIdMetadataKeyPutRaw(requestParameters: ApiV1DataFilesIdMetadataKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MetaDateDTO>> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling apiV1DataFilesIdMetadataKeyPut().'
            );
        }

        if (requestParameters['key'] == null) {
            throw new runtime.RequiredError(
                'key',
                'Required parameter "key" was null or undefined when calling apiV1DataFilesIdMetadataKeyPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/octet-stream';


        let urlPath = `/api/v1/data/files/{id}/metadata/{key}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"key"}}`, encodeURIComponent(String(requestParameters['key'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: requestParameters['body'] as any,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MetaDateDTOFromJSON(jsonValue));
    }

    /**
     * Adds or sets meta documents for a file.
     */
    async apiV1DataFilesIdMetadataKeyPut(requestParameters: ApiV1DataFilesIdMetadataKeyPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MetaDateDTO> {
        const response = await this.apiV1DataFilesIdMetadataKeyPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
