/**
 * My API v1
 * API Version v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

/**
 * Enum indicating whether a dataset was just created or all associated files  were linked. Remember design decision: datasets shall be immutable.
 */
    /**
    * Enum indicating whether a dataset was just created or all associated files  were linked. Remember design decision: datasets shall be immutable.
    */
export enum DataSetStateDTO {
    NUMBER_0 = <any> 0,
    NUMBER_1 = <any> 1
}
