/**
 * My API v1
 * API Version v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as models from './models';

export interface ProblemDetails {
    [key: string]: any | any;

    type?: string;

    title?: string;

    status?: number;

    detail?: string;

    instance?: string;

}
