/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { FileDetailedDTO } from './FileDetailedDTO';
import {
    instanceOfFileDetailedDTO,
    FileDetailedDTOFromJSON,
    FileDetailedDTOFromJSONTyped,
    FileDetailedDTOToJSON,
} from './FileDetailedDTO';
import type { FileMetadataSummaryDTO } from './FileMetadataSummaryDTO';
import {
    instanceOfFileMetadataSummaryDTO,
    FileMetadataSummaryDTOFromJSON,
    FileMetadataSummaryDTOFromJSONTyped,
    FileMetadataSummaryDTOToJSON,
} from './FileMetadataSummaryDTO';
import type { FileSummaryDTO } from './FileSummaryDTO';
import {
    instanceOfFileSummaryDTO,
    FileSummaryDTOFromJSON,
    FileSummaryDTOFromJSONTyped,
    FileSummaryDTOToJSON,
} from './FileSummaryDTO';

/**
 * @type ApiV1DataFilesGet200ResponseInner
 * 
 * @export
 */
export type ApiV1DataFilesGet200ResponseInner = FileDetailedDTO | FileMetadataSummaryDTO | FileSummaryDTO;

export function ApiV1DataFilesGet200ResponseInnerFromJSON(json: any): ApiV1DataFilesGet200ResponseInner {
    return ApiV1DataFilesGet200ResponseInnerFromJSONTyped(json, false);
}

export function ApiV1DataFilesGet200ResponseInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiV1DataFilesGet200ResponseInner {
    if (json == null) {
        return json;
    }
    if (typeof json !== 'object') {
        return json;
    }
    if (instanceOfFileDetailedDTO(json)) {
        return FileDetailedDTOFromJSONTyped(json, true);
    }
    if (instanceOfFileMetadataSummaryDTO(json)) {
        return FileMetadataSummaryDTOFromJSONTyped(json, true);
    }
    if (instanceOfFileSummaryDTO(json)) {
        return FileSummaryDTOFromJSONTyped(json, true);
    }
    return {} as any;
}

export function ApiV1DataFilesGet200ResponseInnerToJSON(json: any): any {
    return ApiV1DataFilesGet200ResponseInnerToJSONTyped(json, false);
}

export function ApiV1DataFilesGet200ResponseInnerToJSONTyped(value?: ApiV1DataFilesGet200ResponseInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    if (typeof value !== 'object') {
        return value;
    }
    if (instanceOfFileDetailedDTO(value)) {
        return FileDetailedDTOToJSON(value as FileDetailedDTO);
    }
    if (instanceOfFileMetadataSummaryDTO(value)) {
        return FileMetadataSummaryDTOToJSON(value as FileMetadataSummaryDTO);
    }
    if (instanceOfFileSummaryDTO(value)) {
        return FileSummaryDTOToJSON(value as FileSummaryDTO);
    }
    return {};
}

