/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetaDateDTO } from './MetaDateDTO';
import {
    MetaDateDTOFromJSON,
    MetaDateDTOFromJSONTyped,
    MetaDateDTOToJSON,
    MetaDateDTOToJSONTyped,
} from './MetaDateDTO';

/**
 * 
 * @export
 * @interface AssignedMetaDateDTO
 */
export interface AssignedMetaDateDTO {
    /**
     * Key linking an entity to a meta date.
     * @type {string}
     * @memberof AssignedMetaDateDTO
     */
    metadataKey?: string | null;
    /**
     * Id of the meta date.
     * @type {string}
     * @memberof AssignedMetaDateDTO
     */
    metadataId?: string | null;
    /**
     * 
     * @type {MetaDateDTO}
     * @memberof AssignedMetaDateDTO
     */
    field?: MetaDateDTO;
    /**
     * Whether this meta date is inherited from the parent collection.
     * @type {boolean}
     * @memberof AssignedMetaDateDTO
     */
    inherited?: boolean | null;
    /**
     * Whether the schema, the collection declares for this key, has been verified.
     * @type {boolean}
     * @memberof AssignedMetaDateDTO
     */
    collectionSchemaVerified?: boolean | null;
}

/**
 * Check if a given object implements the AssignedMetaDateDTO interface.
 */
export function instanceOfAssignedMetaDateDTO(value: object): value is AssignedMetaDateDTO {
    return true;
}

export function AssignedMetaDateDTOFromJSON(json: any): AssignedMetaDateDTO {
    return AssignedMetaDateDTOFromJSONTyped(json, false);
}

export function AssignedMetaDateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AssignedMetaDateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'metadataKey': json['metadataKey'] == null ? undefined : json['metadataKey'],
        'metadataId': json['metadataId'] == null ? undefined : json['metadataId'],
        'field': json['field'] == null ? undefined : MetaDateDTOFromJSON(json['field']),
        'inherited': json['inherited'] == null ? undefined : json['inherited'],
        'collectionSchemaVerified': json['collectionSchemaVerified'] == null ? undefined : json['collectionSchemaVerified'],
    };
}

export function AssignedMetaDateDTOToJSON(json: any): AssignedMetaDateDTO {
    return AssignedMetaDateDTOToJSONTyped(json, false);
}

export function AssignedMetaDateDTOToJSONTyped(value?: AssignedMetaDateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadataKey': value['metadataKey'],
        'metadataId': value['metadataId'],
        'field': MetaDateDTOToJSON(value['field']),
        'inherited': value['inherited'],
        'collectionSchemaVerified': value['collectionSchemaVerified'],
    };
}

