/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MetaDateCollectionColumnDTO } from './MetaDateCollectionColumnDTO';
import {
    MetaDateCollectionColumnDTOFromJSON,
    MetaDateCollectionColumnDTOFromJSONTyped,
    MetaDateCollectionColumnDTOToJSON,
    MetaDateCollectionColumnDTOToJSONTyped,
} from './MetaDateCollectionColumnDTO';

/**
 * 
 * @export
 * @interface CollectionDetailedDTO
 */
export interface CollectionDetailedDTO {
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedDTO
     */
    slug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedDTO
     */
    description?: string | null;
    /**
     * Count of active (deletion neither pending nor completed) datasets in this collection.
     * @type {number}
     * @memberof CollectionDetailedDTO
     */
    dataSetCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedDTO
     */
    defaultDataStoreId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionDetailedDTO
     */
    projectId?: string | null;
    /**
     * 
     * @type {Array<MetaDateCollectionColumnDTO>}
     * @memberof CollectionDetailedDTO
     */
    metaDateColumns?: Array<MetaDateCollectionColumnDTO> | null;
}

/**
 * Check if a given object implements the CollectionDetailedDTO interface.
 */
export function instanceOfCollectionDetailedDTO(value: object): value is CollectionDetailedDTO {
    return true;
}

export function CollectionDetailedDTOFromJSON(json: any): CollectionDetailedDTO {
    return CollectionDetailedDTOFromJSONTyped(json, false);
}

export function CollectionDetailedDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionDetailedDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'description': json['description'] == null ? undefined : json['description'],
        'dataSetCount': json['dataSetCount'] == null ? undefined : json['dataSetCount'],
        'defaultDataStoreId': json['defaultDataStoreId'] == null ? undefined : json['defaultDataStoreId'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
        'metaDateColumns': json['metaDateColumns'] == null ? undefined : ((json['metaDateColumns'] as Array<any>).map(MetaDateCollectionColumnDTOFromJSON)),
    };
}

export function CollectionDetailedDTOToJSON(json: any): CollectionDetailedDTO {
    return CollectionDetailedDTOToJSONTyped(json, false);
}

export function CollectionDetailedDTOToJSONTyped(value?: CollectionDetailedDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'name': value['name'],
        'description': value['description'],
        'dataSetCount': value['dataSetCount'],
        'defaultDataStoreId': value['defaultDataStoreId'],
        'projectId': value['projectId'],
        'metaDateColumns': value['metaDateColumns'] == null ? undefined : ((value['metaDateColumns'] as Array<any>).map(MetaDateCollectionColumnDTOToJSON)),
    };
}

