/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CollectionSummaryDTO
 */
export interface CollectionSummaryDTO {
    /**
     * 
     * @type {string}
     * @memberof CollectionSummaryDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionSummaryDTO
     */
    slug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionSummaryDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof CollectionSummaryDTO
     */
    dataSetCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof CollectionSummaryDTO
     */
    defaultDataStoreId?: string | null;
}

/**
 * Check if a given object implements the CollectionSummaryDTO interface.
 */
export function instanceOfCollectionSummaryDTO(value: object): value is CollectionSummaryDTO {
    return true;
}

export function CollectionSummaryDTOFromJSON(json: any): CollectionSummaryDTO {
    return CollectionSummaryDTOFromJSONTyped(json, false);
}

export function CollectionSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CollectionSummaryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'dataSetCount': json['dataSetCount'] == null ? undefined : json['dataSetCount'],
        'defaultDataStoreId': json['defaultDataStoreId'] == null ? undefined : json['defaultDataStoreId'],
    };
}

export function CollectionSummaryDTOToJSON(value?: CollectionSummaryDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'name': value['name'],
        'dataSetCount': value['dataSetCount'],
        'defaultDataStoreId': value['defaultDataStoreId'],
    };
}

