/* tslint:disable */
/* eslint-disable */
/**
 * My API v1
 * API Version v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContainerSummaryDTO
 */
export interface ContainerSummaryDTO {
    /**
     * 
     * @type {string}
     * @memberof ContainerSummaryDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContainerSummaryDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof ContainerSummaryDTO
     */
    dataFilesCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof ContainerSummaryDTO
     */
    defaultDataStoreId?: string | null;
}

/**
 * Check if a given object implements the ContainerSummaryDTO interface.
 */
export function instanceOfContainerSummaryDTO(value: object): value is ContainerSummaryDTO {
    return true;
}

export function ContainerSummaryDTOFromJSON(json: any): ContainerSummaryDTO {
    return ContainerSummaryDTOFromJSONTyped(json, false);
}

export function ContainerSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContainerSummaryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'dataFilesCount': json['dataFilesCount'] == null ? undefined : json['dataFilesCount'],
        'defaultDataStoreId': json['defaultDataStoreId'] == null ? undefined : json['defaultDataStoreId'],
    };
}

export function ContainerSummaryDTOToJSON(value?: ContainerSummaryDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'dataFilesCount': value['dataFilesCount'],
        'defaultDataStoreId': value['defaultDataStoreId'],
    };
}

