/* tslint:disable */
/* eslint-disable */
/**
 * My API v1
 * API Version v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ContentTypeDTO
 */
export interface ContentTypeDTO {
    /**
     * 
     * @type {string}
     * @memberof ContentTypeDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentTypeDTO
     */
    abbreviation?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentTypeDTO
     */
    displayName?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentTypeDTO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ContentTypeDTO
     */
    mimeType?: string | null;
}

/**
 * Check if a given object implements the ContentTypeDTO interface.
 */
export function instanceOfContentTypeDTO(value: object): value is ContentTypeDTO {
    return true;
}

export function ContentTypeDTOFromJSON(json: any): ContentTypeDTO {
    return ContentTypeDTOFromJSONTyped(json, false);
}

export function ContentTypeDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ContentTypeDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'abbreviation': json['abbreviation'] == null ? undefined : json['abbreviation'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'description': json['description'] == null ? undefined : json['description'],
        'mimeType': json['mimeType'] == null ? undefined : json['mimeType'],
    };
}

export function ContentTypeDTOToJSON(value?: ContentTypeDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'abbreviation': value['abbreviation'],
        'displayName': value['displayName'],
        'description': value['description'],
        'mimeType': value['mimeType'],
    };
}

