/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DataStoreSummaryDTO
 */
export interface DataStoreSummaryDTO {
    /**
     * 
     * @type {string}
     * @memberof DataStoreSummaryDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataStoreSummaryDTO
     */
    slug?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataStoreSummaryDTO
     */
    name?: string | null;
    /**
     * 
     * @type {number}
     * @memberof DataStoreSummaryDTO
     */
    filesCount?: number | null;
    /**
     * 
     * @type {string}
     * @memberof DataStoreSummaryDTO
     */
    storageType?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataStoreSummaryDTO
     */
    propertiesJson?: string | null;
    /**
     * 
     * @type {string}
     * @memberof DataStoreSummaryDTO
     */
    projectId?: string | null;
}

/**
 * Check if a given object implements the DataStoreSummaryDTO interface.
 */
export function instanceOfDataStoreSummaryDTO(value: object): value is DataStoreSummaryDTO {
    return true;
}

export function DataStoreSummaryDTOFromJSON(json: any): DataStoreSummaryDTO {
    return DataStoreSummaryDTOFromJSONTyped(json, false);
}

export function DataStoreSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataStoreSummaryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'filesCount': json['filesCount'] == null ? undefined : json['filesCount'],
        'storageType': json['storageType'] == null ? undefined : json['storageType'],
        'propertiesJson': json['propertiesJson'] == null ? undefined : json['propertiesJson'],
        'projectId': json['projectId'] == null ? undefined : json['projectId'],
    };
}

export function DataStoreSummaryDTOToJSON(json: any): DataStoreSummaryDTO {
    return DataStoreSummaryDTOToJSONTyped(json, false);
}

export function DataStoreSummaryDTOToJSONTyped(value?: DataStoreSummaryDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'name': value['name'],
        'filesCount': value['filesCount'],
        'storageType': value['storageType'],
        'propertiesJson': value['propertiesJson'],
        'projectId': value['projectId'],
    };
}

