/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * Request body for creating a new dataset.
 * Kept non-polymorphic on purpose to avoid discriminator/subtype binding issues.
 * @export
 * @interface DataSetCreateRequestDTO
 */
export interface DataSetCreateRequestDTO {
    /**
     * Optional human-readable identifier.
     * @type {string}
     * @memberof DataSetCreateRequestDTO
     */
    slug?: string | null;
    /**
     * Mandatory dataset name.
     * @type {string}
     * @memberof DataSetCreateRequestDTO
     */
    name?: string | null;
    /**
     * Mandatory creation timestamp in UTC.
     * @type {Date}
     * @memberof DataSetCreateRequestDTO
     */
    createdStampUTC?: Date | null;
    /**
     * Mandatory parent collection id.
     * @type {string}
     * @memberof DataSetCreateRequestDTO
     */
    collectionId?: string | null;
}

/**
 * Check if a given object implements the DataSetCreateRequestDTO interface.
 */
export function instanceOfDataSetCreateRequestDTO(value: object): value is DataSetCreateRequestDTO {
    return true;
}

export function DataSetCreateRequestDTOFromJSON(json: any): DataSetCreateRequestDTO {
    return DataSetCreateRequestDTOFromJSONTyped(json, false);
}

export function DataSetCreateRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSetCreateRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdStampUTC': json['createdStampUTC'] == null ? undefined : (new Date(json['createdStampUTC'])),
        'collectionId': json['collectionId'] == null ? undefined : json['collectionId'],
    };
}

export function DataSetCreateRequestDTOToJSON(json: any): DataSetCreateRequestDTO {
    return DataSetCreateRequestDTOToJSONTyped(json, false);
}

export function DataSetCreateRequestDTOToJSONTyped(value?: DataSetCreateRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'createdStampUTC': value['createdStampUTC'] == null ? value['createdStampUTC'] : value['createdStampUTC'].toISOString(),
        'collectionId': value['collectionId'],
    };
}

