/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssignedMetaDateDTO } from './AssignedMetaDateDTO';
import {
    AssignedMetaDateDTOFromJSON,
    AssignedMetaDateDTOFromJSONTyped,
    AssignedMetaDateDTOToJSON,
    AssignedMetaDateDTOToJSONTyped,
} from './AssignedMetaDateDTO';
import type { DeletionStateDTO } from './DeletionStateDTO';
import {
    DeletionStateDTOFromJSON,
    DeletionStateDTOFromJSONTyped,
    DeletionStateDTOToJSON,
    DeletionStateDTOToJSONTyped,
} from './DeletionStateDTO';
import type { TagDTO } from './TagDTO';
import {
    TagDTOFromJSON,
    TagDTOFromJSONTyped,
    TagDTOToJSON,
    TagDTOToJSONTyped,
} from './TagDTO';
import type { FileMetadataSummaryDTO } from './FileMetadataSummaryDTO';
import {
    FileMetadataSummaryDTOFromJSON,
    FileMetadataSummaryDTOFromJSONTyped,
    FileMetadataSummaryDTOToJSON,
    FileMetadataSummaryDTOToJSONTyped,
} from './FileMetadataSummaryDTO';
import type { DataSetSummaryDTO } from './DataSetSummaryDTO';
import {
    DataSetSummaryDTOFromJSON,
    DataSetSummaryDTOFromJSONTyped,
    DataSetSummaryDTOToJSON,
    DataSetSummaryDTOToJSONTyped,
} from './DataSetSummaryDTO';

/**
 * 
 * @export
 * @interface DataSetFileMetadataSummaryDTO
 */
export interface DataSetFileMetadataSummaryDTO extends DataSetSummaryDTO {
    /**
     * 
     * @type {Array<FileMetadataSummaryDTO>}
     * @memberof DataSetFileMetadataSummaryDTO
     */
    files?: Array<FileMetadataSummaryDTO> | null;
}



/**
 * Check if a given object implements the DataSetFileMetadataSummaryDTO interface.
 */
export function instanceOfDataSetFileMetadataSummaryDTO(value: object): value is DataSetFileMetadataSummaryDTO {
    return true;
}

export function DataSetFileMetadataSummaryDTOFromJSON(json: any): DataSetFileMetadataSummaryDTO {
    return DataSetFileMetadataSummaryDTOFromJSONTyped(json, false);
}

export function DataSetFileMetadataSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSetFileMetadataSummaryDTO {
    if (json == null) {
        return json;
    }
    return {
        ...DataSetSummaryDTOFromJSONTyped(json, true),
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(FileMetadataSummaryDTOFromJSON)),
    };
}

export function DataSetFileMetadataSummaryDTOToJSON(json: any): DataSetFileMetadataSummaryDTO {
    return DataSetFileMetadataSummaryDTOToJSONTyped(json, false);
}

export function DataSetFileMetadataSummaryDTOToJSONTyped(value?: DataSetFileMetadataSummaryDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...DataSetSummaryDTOToJSONTyped(value, true),
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(FileMetadataSummaryDTOToJSON)),
    };
}

