/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssignedMetaDateDTO } from './AssignedMetaDateDTO';
import {
    AssignedMetaDateDTOFromJSON,
    AssignedMetaDateDTOFromJSONTyped,
    AssignedMetaDateDTOToJSON,
    AssignedMetaDateDTOToJSONTyped,
} from './AssignedMetaDateDTO';
import type { DeletionStateDTO } from './DeletionStateDTO';
import {
    DeletionStateDTOFromJSON,
    DeletionStateDTOFromJSONTyped,
    DeletionStateDTOToJSON,
    DeletionStateDTOToJSONTyped,
} from './DeletionStateDTO';
import type { TagDTO } from './TagDTO';
import {
    TagDTOFromJSON,
    TagDTOFromJSONTyped,
    TagDTOToJSON,
    TagDTOToJSONTyped,
} from './TagDTO';

/**
 * Represents a summary of a dataset, including identifying information, timestamps, state, tags,
 * and metadata fields.
 * @export
 * @interface DataSetSummaryDTO
 */
export interface DataSetSummaryDTO {
    /**
     * Uniquely identifies the dataset. Typically server-generated. Should not be manually set by the client.
     * @type {string}
     * @memberof DataSetSummaryDTO
     */
    id?: string | null;
    /**
     * An optional, human-readable identifier for the dataset.
     * @type {string}
     * @memberof DataSetSummaryDTO
     */
    slug?: string | null;
    /**
     * Non-unique, mandatory descriptive name of the dataset. Must be provided by the client.
     * @type {string}
     * @memberof DataSetSummaryDTO
     */
    name?: string | null;
    /**
     * List of tags associated with the dataset, used for categorization and filtering purposes.
     * @type {Array<TagDTO>}
     * @memberof DataSetSummaryDTO
     */
    assignedTags?: Array<TagDTO> | null;
    /**
     * UTC timestamp when the dataset was originally created.
     * Mandatory property, should be provided by the client.
     * @type {Date}
     * @memberof DataSetSummaryDTO
     */
    createdStampUTC?: Date | null;
    /**
     * UTC timestamp that indicates when the dataset was deleted.
     * Null if the dataset has not been deleted yet.
     * @type {Date}
     * @memberof DataSetSummaryDTO
     */
    deletedStampUTC?: Date | null;
    /**
     * UTC timestamp that marks the period begin of the dataset.
     * Only to be set by server.
     * @type {Date}
     * @memberof DataSetSummaryDTO
     */
    beginStampUTC?: Date | null;
    /**
     * UTC timestamp that marks the period end of the dataset.
     * Only to be set by server.
     * @type {Date}
     * @memberof DataSetSummaryDTO
     */
    endStampUTC?: Date | null;
    /**
     * Indicates, whether the dataset (and its files) are immutable.
     * Only to be set by server.
     * Lifecycle is: Uninitialized -> Sealed
     * @type {string}
     * @memberof DataSetSummaryDTO
     */
    lifecycleState?: string | null;
    /**
     * 
     * @type {DeletionStateDTO}
     * @memberof DataSetSummaryDTO
     */
    deletionState?: DeletionStateDTO;
    /**
     * Indicates if the dataset represents time-series data.
     * Only to be set by server.
     * @type {boolean}
     * @memberof DataSetSummaryDTO
     */
    isTimeSeries?: boolean | null;
    /**
     * Fields, for which metadata exists.
     * Only to be set by server.
     * @type {Array<AssignedMetaDateDTO>}
     * @memberof DataSetSummaryDTO
     */
    metaDates?: Array<AssignedMetaDateDTO> | null;
    /**
     * Amount of files in the dataset.
     * @type {number}
     * @memberof DataSetSummaryDTO
     */
    fileCount?: number;
    /**
     * Id of the collection this dataset belongs to.
     * @type {string}
     * @memberof DataSetSummaryDTO
     */
    collectionId?: string | null;
}



/**
 * Check if a given object implements the DataSetSummaryDTO interface.
 */
export function instanceOfDataSetSummaryDTO(value: object): value is DataSetSummaryDTO {
    return true;
}

export function DataSetSummaryDTOFromJSON(json: any): DataSetSummaryDTO {
    return DataSetSummaryDTOFromJSONTyped(json, false);
}

export function DataSetSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSetSummaryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'assignedTags': json['assignedTags'] == null ? undefined : ((json['assignedTags'] as Array<any>).map(TagDTOFromJSON)),
        'createdStampUTC': json['createdStampUTC'] == null ? undefined : (new Date(json['createdStampUTC'])),
        'deletedStampUTC': json['deletedStampUTC'] == null ? undefined : (new Date(json['deletedStampUTC'])),
        'beginStampUTC': json['beginStampUTC'] == null ? undefined : (new Date(json['beginStampUTC'])),
        'endStampUTC': json['endStampUTC'] == null ? undefined : (new Date(json['endStampUTC'])),
        'lifecycleState': json['lifecycleState'] == null ? undefined : json['lifecycleState'],
        'deletionState': json['deletionState'] == null ? undefined : DeletionStateDTOFromJSON(json['deletionState']),
        'isTimeSeries': json['isTimeSeries'] == null ? undefined : json['isTimeSeries'],
        'metaDates': json['metaDates'] == null ? undefined : ((json['metaDates'] as Array<any>).map(AssignedMetaDateDTOFromJSON)),
        'fileCount': json['fileCount'] == null ? undefined : json['fileCount'],
        'collectionId': json['collectionId'] == null ? undefined : json['collectionId'],
    };
}

export function DataSetSummaryDTOToJSON(json: any): DataSetSummaryDTO {
    return DataSetSummaryDTOToJSONTyped(json, false);
}

export function DataSetSummaryDTOToJSONTyped(value?: DataSetSummaryDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'slug': value['slug'],
        'name': value['name'],
        'assignedTags': value['assignedTags'] == null ? undefined : ((value['assignedTags'] as Array<any>).map(TagDTOToJSON)),
        'createdStampUTC': value['createdStampUTC'] == null ? value['createdStampUTC'] : value['createdStampUTC'].toISOString(),
        'deletedStampUTC': value['deletedStampUTC'] == null ? value['deletedStampUTC'] : value['deletedStampUTC'].toISOString(),
        'beginStampUTC': value['beginStampUTC'] == null ? value['beginStampUTC'] : value['beginStampUTC'].toISOString(),
        'endStampUTC': value['endStampUTC'] == null ? value['endStampUTC'] : value['endStampUTC'].toISOString(),
        'lifecycleState': value['lifecycleState'],
        'deletionState': DeletionStateDTOToJSON(value['deletionState']),
        'isTimeSeries': value['isTimeSeries'],
        'metaDates': value['metaDates'] == null ? undefined : ((value['metaDates'] as Array<any>).map(AssignedMetaDateDTOToJSON)),
        'fileCount': value['fileCount'],
        'collectionId': value['collectionId'],
    };
}

