/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssignedMetaDateDTO } from './AssignedMetaDateDTO';
import {
    AssignedMetaDateDTOFromJSON,
    AssignedMetaDateDTOFromJSONTyped,
    AssignedMetaDateDTOToJSON,
    AssignedMetaDateDTOToJSONTyped,
} from './AssignedMetaDateDTO';
import type { DataSetDetailedDTOAllOfFiles } from './DataSetDetailedDTOAllOfFiles';
import {
    DataSetDetailedDTOAllOfFilesFromJSON,
    DataSetDetailedDTOAllOfFilesFromJSONTyped,
    DataSetDetailedDTOAllOfFilesToJSON,
    DataSetDetailedDTOAllOfFilesToJSONTyped,
} from './DataSetDetailedDTOAllOfFiles';
import type { DeletionStateDTO } from './DeletionStateDTO';
import {
    DeletionStateDTOFromJSON,
    DeletionStateDTOFromJSONTyped,
    DeletionStateDTOToJSON,
    DeletionStateDTOToJSONTyped,
} from './DeletionStateDTO';
import type { TagDTO } from './TagDTO';
import {
    TagDTOFromJSON,
    TagDTOFromJSONTyped,
    TagDTOToJSON,
    TagDTOToJSONTyped,
} from './TagDTO';
import type { DataSetSummaryDTO } from './DataSetSummaryDTO';
import {
    DataSetSummaryDTOFromJSON,
    DataSetSummaryDTOFromJSONTyped,
    DataSetSummaryDTOToJSON,
    DataSetSummaryDTOToJSONTyped,
} from './DataSetSummaryDTO';

/**
 * Represents a summary of a dataset, including identifying information, timestamps, state, tags,
 * and metadata fields.
 * @export
 * @interface DataSetDetailedDTO
 */
export interface DataSetDetailedDTO extends DataSetSummaryDTO {
    /**
     * 
     * @type {Array<DataSetDetailedDTOAllOfFiles>}
     * @memberof DataSetDetailedDTO
     */
    files?: Array<DataSetDetailedDTOAllOfFiles> | null;
}



/**
 * Check if a given object implements the DataSetDetailedDTO interface.
 */
export function instanceOfDataSetDetailedDTO(value: object): value is DataSetDetailedDTO {
    return true;
}

export function DataSetDetailedDTOFromJSON(json: any): DataSetDetailedDTO {
    return DataSetDetailedDTOFromJSONTyped(json, false);
}

export function DataSetDetailedDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DataSetDetailedDTO {
    if (json == null) {
        return json;
    }
    return {
        ...DataSetSummaryDTOFromJSONTyped(json, true),
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(DataSetDetailedDTOAllOfFilesFromJSON)),
    };
}

export function DataSetDetailedDTOToJSON(json: any): DataSetDetailedDTO {
    return DataSetDetailedDTOToJSONTyped(json, false);
}

export function DataSetDetailedDTOToJSONTyped(value?: DataSetDetailedDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        ...DataSetSummaryDTOToJSONTyped(value, true),
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(DataSetDetailedDTOAllOfFilesToJSON)),
    };
}

