/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Enum indicating whether an entity was deleted.
 * @export
 */
export const DeletionStateDTO = {
    Active: 'Active',
    DeletionPending: 'DeletionPending',
    Deleted: 'Deleted'
} as const;
export type DeletionStateDTO = typeof DeletionStateDTO[keyof typeof DeletionStateDTO];


export function instanceOfDeletionStateDTO(value: any): boolean {
    for (const key in DeletionStateDTO) {
        if (Object.prototype.hasOwnProperty.call(DeletionStateDTO, key)) {
            if ((DeletionStateDTO as Record<string, DeletionStateDTO>)[key] === value) {
                return true;
            }
        }
    }
    return false;
}

export function DeletionStateDTOFromJSON(json: any): DeletionStateDTO {
    return DeletionStateDTOFromJSONTyped(json, false);
}

export function DeletionStateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): DeletionStateDTO {
    return json as DeletionStateDTO;
}

export function DeletionStateDTOToJSON(value?: DeletionStateDTO | null): any {
    return value as any;
}

