/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { JobState } from './JobState';
import {
    JobStateFromJSON,
    JobStateFromJSONTyped,
    JobStateToJSON,
    JobStateToJSONTyped,
} from './JobState';

/**
 * 
 * @export
 * @interface ExecutionSummaryDTO
 */
export interface ExecutionSummaryDTO {
    /**
     * 
     * @type {string}
     * @memberof ExecutionSummaryDTO
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof ExecutionSummaryDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExecutionSummaryDTO
     */
    pipelineKey?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ExecutionSummaryDTO
     */
    trackerId?: string | null;
    /**
     * 
     * @type {JobState}
     * @memberof ExecutionSummaryDTO
     */
    state?: JobState;
    /**
     * 
     * @type {Date}
     * @memberof ExecutionSummaryDTO
     */
    createdStampUtc?: Date;
    /**
     * 
     * @type {Date}
     * @memberof ExecutionSummaryDTO
     */
    startedStampUtc?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof ExecutionSummaryDTO
     */
    terminatedStampUtc?: Date | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExecutionSummaryDTO
     */
    sourceDatasetIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExecutionSummaryDTO
     */
    outputDatasetIds?: Array<string> | null;
    /**
     * 
     * @type {Array<string>}
     * @memberof ExecutionSummaryDTO
     */
    metadataIds?: Array<string> | null;
}



/**
 * Check if a given object implements the ExecutionSummaryDTO interface.
 */
export function instanceOfExecutionSummaryDTO(value: object): value is ExecutionSummaryDTO {
    return true;
}

export function ExecutionSummaryDTOFromJSON(json: any): ExecutionSummaryDTO {
    return ExecutionSummaryDTOFromJSONTyped(json, false);
}

export function ExecutionSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ExecutionSummaryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'pipelineKey': json['pipelineKey'] == null ? undefined : json['pipelineKey'],
        'trackerId': json['trackerId'] == null ? undefined : json['trackerId'],
        'state': json['state'] == null ? undefined : JobStateFromJSON(json['state']),
        'createdStampUtc': json['createdStampUtc'] == null ? undefined : (new Date(json['createdStampUtc'])),
        'startedStampUtc': json['startedStampUtc'] == null ? undefined : (new Date(json['startedStampUtc'])),
        'terminatedStampUtc': json['terminatedStampUtc'] == null ? undefined : (new Date(json['terminatedStampUtc'])),
        'sourceDatasetIds': json['sourceDatasetIds'] == null ? undefined : json['sourceDatasetIds'],
        'outputDatasetIds': json['outputDatasetIds'] == null ? undefined : json['outputDatasetIds'],
        'metadataIds': json['metadataIds'] == null ? undefined : json['metadataIds'],
    };
}

export function ExecutionSummaryDTOToJSON(json: any): ExecutionSummaryDTO {
    return ExecutionSummaryDTOToJSONTyped(json, false);
}

export function ExecutionSummaryDTOToJSONTyped(value?: ExecutionSummaryDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'pipelineKey': value['pipelineKey'],
        'trackerId': value['trackerId'],
        'state': JobStateToJSON(value['state']),
        'createdStampUtc': value['createdStampUtc'] == null ? value['createdStampUtc'] : value['createdStampUtc'].toISOString(),
        'startedStampUtc': value['startedStampUtc'] == null ? value['startedStampUtc'] : value['startedStampUtc'].toISOString(),
        'terminatedStampUtc': value['terminatedStampUtc'] == null ? value['terminatedStampUtc'] : value['terminatedStampUtc'].toISOString(),
        'sourceDatasetIds': value['sourceDatasetIds'],
        'outputDatasetIds': value['outputDatasetIds'],
        'metadataIds': value['metadataIds'],
    };
}

