/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { ContentTypeDTO } from './ContentTypeDTO';
import {
    ContentTypeDTOFromJSON,
    ContentTypeDTOFromJSONTyped,
    ContentTypeDTOToJSON,
    ContentTypeDTOToJSONTyped,
} from './ContentTypeDTO';

/**
 * 
 * @export
 * @interface FileSummaryDTO
 */
export interface FileSummaryDTO {
    /**
     * 
     * @type {string}
     * @memberof FileSummaryDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileSummaryDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileSummaryDTO
     */
    downloadURI?: string | null;
    /**
     * 
     * @type {ContentTypeDTO}
     * @memberof FileSummaryDTO
     */
    contentType?: ContentTypeDTO;
    /**
     * 
     * @type {number}
     * @memberof FileSummaryDTO
     */
    size?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof FileSummaryDTO
     */
    createdStampUTC?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FileSummaryDTO
     */
    deletedStampUTC?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FileSummaryDTO
     */
    beginStampUTC?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FileSummaryDTO
     */
    endStampUTC?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof FileSummaryDTO
     */
    isTimeSeries?: boolean | null;
    /**
     * 
     * @type {boolean}
     * @memberof FileSummaryDTO
     */
    isDeleted?: boolean | null;
}

/**
 * Check if a given object implements the FileSummaryDTO interface.
 */
export function instanceOfFileSummaryDTO(value: object): value is FileSummaryDTO {
    return true;
}

export function FileSummaryDTOFromJSON(json: any): FileSummaryDTO {
    return FileSummaryDTOFromJSONTyped(json, false);
}

export function FileSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileSummaryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'downloadURI': json['downloadURI'] == null ? undefined : json['downloadURI'],
        'contentType': json['contentType'] == null ? undefined : ContentTypeDTOFromJSON(json['contentType']),
        'size': json['size'] == null ? undefined : json['size'],
        'createdStampUTC': json['createdStampUTC'] == null ? undefined : (new Date(json['createdStampUTC'])),
        'deletedStampUTC': json['deletedStampUTC'] == null ? undefined : (new Date(json['deletedStampUTC'])),
        'beginStampUTC': json['beginStampUTC'] == null ? undefined : (new Date(json['beginStampUTC'])),
        'endStampUTC': json['endStampUTC'] == null ? undefined : (new Date(json['endStampUTC'])),
        'isTimeSeries': json['isTimeSeries'] == null ? undefined : json['isTimeSeries'],
        'isDeleted': json['isDeleted'] == null ? undefined : json['isDeleted'],
    };
}

export function FileSummaryDTOToJSON(json: any): FileSummaryDTO {
    return FileSummaryDTOToJSONTyped(json, false);
}

export function FileSummaryDTOToJSONTyped(value?: FileSummaryDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'name': value['name'],
        'downloadURI': value['downloadURI'],
        'contentType': ContentTypeDTOToJSON(value['contentType']),
        'size': value['size'],
        'createdStampUTC': value['createdStampUTC'] == null ? value['createdStampUTC'] : value['createdStampUTC'].toISOString(),
        'deletedStampUTC': value['deletedStampUTC'] == null ? value['deletedStampUTC'] : value['deletedStampUTC'].toISOString(),
        'beginStampUTC': value['beginStampUTC'] == null ? value['beginStampUTC'] : value['beginStampUTC'].toISOString(),
        'endStampUTC': value['endStampUTC'] == null ? value['endStampUTC'] : value['endStampUTC'].toISOString(),
        'isTimeSeries': value['isTimeSeries'],
        'isDeleted': value['isDeleted'],
    };
}

