/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssignedMetaDateDTO } from './AssignedMetaDateDTO';
import {
    AssignedMetaDateDTOFromJSON,
    AssignedMetaDateDTOFromJSONTyped,
    AssignedMetaDateDTOToJSON,
    AssignedMetaDateDTOToJSONTyped,
} from './AssignedMetaDateDTO';
import type { ContentTypeDTO } from './ContentTypeDTO';
import {
    ContentTypeDTOFromJSON,
    ContentTypeDTOFromJSONTyped,
    ContentTypeDTOToJSON,
    ContentTypeDTOToJSONTyped,
} from './ContentTypeDTO';
import type { DeletionStateDTO } from './DeletionStateDTO';
import {
    DeletionStateDTOFromJSON,
    DeletionStateDTOFromJSONTyped,
    DeletionStateDTOToJSON,
    DeletionStateDTOToJSONTyped,
} from './DeletionStateDTO';

import { type FileDetailedDTO, FileDetailedDTOFromJSONTyped, FileDetailedDTOToJSON, FileDetailedDTOToJSONTyped } from './FileDetailedDTO';
import { type FileMetadataSummaryDTO, FileMetadataSummaryDTOFromJSONTyped, FileMetadataSummaryDTOToJSON, FileMetadataSummaryDTOToJSONTyped } from './FileMetadataSummaryDTO';
/**
 * 
 * @export
 * @interface FileSummaryDTO
 */
export interface FileSummaryDTO {
    /**
     * 
     * @type {string}
     * @memberof FileSummaryDTO
     */
    kind: string;
    /**
     * 
     * @type {string}
     * @memberof FileSummaryDTO
     */
    id?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileSummaryDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileSummaryDTO
     */
    downloadURI?: string | null;
    /**
     * 
     * @type {ContentTypeDTO}
     * @memberof FileSummaryDTO
     */
    contentType?: ContentTypeDTO;
    /**
     * 
     * @type {number}
     * @memberof FileSummaryDTO
     */
    size?: number | null;
    /**
     * 
     * @type {Date}
     * @memberof FileSummaryDTO
     */
    createdStampUTC?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FileSummaryDTO
     */
    deletedStampUTC?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FileSummaryDTO
     */
    beginStampUTC?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FileSummaryDTO
     */
    endStampUTC?: Date | null;
    /**
     * 
     * @type {boolean}
     * @memberof FileSummaryDTO
     */
    isTimeSeries?: boolean | null;
    /**
     * Fields, for which metadata exists.
     * Only to be set by server.
     * @type {Array<AssignedMetaDateDTO>}
     * @memberof FileSummaryDTO
     */
    metaDates?: Array<AssignedMetaDateDTO> | null;
    /**
     * 
     * @type {DeletionStateDTO}
     * @memberof FileSummaryDTO
     */
    deletionState?: DeletionStateDTO;
}



/**
 * Check if a given object implements the FileSummaryDTO interface.
 */
export function instanceOfFileSummaryDTO(value: object): value is FileSummaryDTO {
    if (!('kind' in value) || value['kind'] === undefined) return false;
    return true;
}

export function FileSummaryDTOFromJSON(json: any): FileSummaryDTO {
    return FileSummaryDTOFromJSONTyped(json, false);
}

export function FileSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileSummaryDTO {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['kind'] === 'detailed') {
            return FileDetailedDTOFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['kind'] === 'metadata') {
            return FileMetadataSummaryDTOFromJSONTyped(json, ignoreDiscriminator);
        }
        if (json['kind'] === 'summary') {
            return FileSummaryDTOFromJSONTyped(json, true);
        }

    }
    return {
        
        'kind': json['kind'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'downloadURI': json['downloadURI'] == null ? undefined : json['downloadURI'],
        'contentType': json['contentType'] == null ? undefined : ContentTypeDTOFromJSON(json['contentType']),
        'size': json['size'] == null ? undefined : json['size'],
        'createdStampUTC': json['createdStampUTC'] == null ? undefined : (new Date(json['createdStampUTC'])),
        'deletedStampUTC': json['deletedStampUTC'] == null ? undefined : (new Date(json['deletedStampUTC'])),
        'beginStampUTC': json['beginStampUTC'] == null ? undefined : (new Date(json['beginStampUTC'])),
        'endStampUTC': json['endStampUTC'] == null ? undefined : (new Date(json['endStampUTC'])),
        'isTimeSeries': json['isTimeSeries'] == null ? undefined : json['isTimeSeries'],
        'metaDates': json['metaDates'] == null ? undefined : ((json['metaDates'] as Array<any>).map(AssignedMetaDateDTOFromJSON)),
        'deletionState': json['deletionState'] == null ? undefined : DeletionStateDTOFromJSON(json['deletionState']),
    };
}

export function FileSummaryDTOToJSON(json: any): FileSummaryDTO {
    return FileSummaryDTOToJSONTyped(json, false);
}

export function FileSummaryDTOToJSONTyped(value?: FileSummaryDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (!ignoreDiscriminator) {
        switch (value['kind']) {
            case 'detailed':
                return FileDetailedDTOToJSONTyped(value as FileDetailedDTO, ignoreDiscriminator);
            case 'metadata':
                return FileMetadataSummaryDTOToJSONTyped(value as FileMetadataSummaryDTO, ignoreDiscriminator);
            default:
                return value;
        }
    }

    return {
        
        'kind': value['kind'],
        'id': value['id'],
        'name': value['name'],
        'downloadURI': value['downloadURI'],
        'contentType': ContentTypeDTOToJSON(value['contentType']),
        'size': value['size'],
        'createdStampUTC': value['createdStampUTC'] == null ? value['createdStampUTC'] : value['createdStampUTC'].toISOString(),
        'deletedStampUTC': value['deletedStampUTC'] == null ? value['deletedStampUTC'] : value['deletedStampUTC'].toISOString(),
        'beginStampUTC': value['beginStampUTC'] == null ? value['beginStampUTC'] : value['beginStampUTC'].toISOString(),
        'endStampUTC': value['endStampUTC'] == null ? value['endStampUTC'] : value['endStampUTC'].toISOString(),
        'isTimeSeries': value['isTimeSeries'],
        'metaDates': value['metaDates'] == null ? undefined : ((value['metaDates'] as Array<any>).map(AssignedMetaDateDTOToJSON)),
        'deletionState': DeletionStateDTOToJSON(value['deletionState']),
    };
}

