/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AssignedMetaDateDTO } from './AssignedMetaDateDTO';
import {
    AssignedMetaDateDTOFromJSON,
    AssignedMetaDateDTOFromJSONTyped,
    AssignedMetaDateDTOToJSON,
    AssignedMetaDateDTOToJSONTyped,
} from './AssignedMetaDateDTO';
import type { FileSummaryDTO } from './FileSummaryDTO';
import {
    FileSummaryDTOFromJSON,
    FileSummaryDTOFromJSONTyped,
    FileSummaryDTOToJSON,
    FileSummaryDTOToJSONTyped,
} from './FileSummaryDTO';
import type { ContentTypeDTO } from './ContentTypeDTO';
import {
    ContentTypeDTOFromJSON,
    ContentTypeDTOFromJSONTyped,
    ContentTypeDTOToJSON,
    ContentTypeDTOToJSONTyped,
} from './ContentTypeDTO';
import type { DeletionStateDTO } from './DeletionStateDTO';
import {
    DeletionStateDTOFromJSON,
    DeletionStateDTOFromJSONTyped,
    DeletionStateDTOToJSON,
    DeletionStateDTOToJSONTyped,
} from './DeletionStateDTO';

/**
 * 
 * @export
 * @interface FileMetadataSummaryDTO
 */
export interface FileMetadataSummaryDTO extends FileSummaryDTO {
}



/**
 * Check if a given object implements the FileMetadataSummaryDTO interface.
 */
export function instanceOfFileMetadataSummaryDTO(value: object): value is FileMetadataSummaryDTO {
    return true;
}

export function FileMetadataSummaryDTOFromJSON(json: any): FileMetadataSummaryDTO {
    return FileMetadataSummaryDTOFromJSONTyped(json, false);
}

export function FileMetadataSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileMetadataSummaryDTO {
    return json;
}

export function FileMetadataSummaryDTOToJSON(json: any): FileMetadataSummaryDTO {
    return FileMetadataSummaryDTOToJSONTyped(json, false);
}

export function FileMetadataSummaryDTOToJSONTyped(value?: FileMetadataSummaryDTO | null, ignoreDiscriminator: boolean = false): any {
    return value;
}

