/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileCreateRequestDTO
 */
export interface FileCreateRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof FileCreateRequestDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileCreateRequestDTO
     */
    contentTypeId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FileCreateRequestDTO
     */
    sizeBytes?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FileCreateRequestDTO
     */
    plainSHA256Hash?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FileCreateRequestDTO
     */
    createdStamp?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FileCreateRequestDTO
     */
    beginStamp?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FileCreateRequestDTO
     */
    endStamp?: Date | null;
}

/**
 * Check if a given object implements the FileCreateRequestDTO interface.
 */
export function instanceOfFileCreateRequestDTO(value: object): value is FileCreateRequestDTO {
    return true;
}

export function FileCreateRequestDTOFromJSON(json: any): FileCreateRequestDTO {
    return FileCreateRequestDTOFromJSONTyped(json, false);
}

export function FileCreateRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileCreateRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'contentTypeId': json['contentTypeId'] == null ? undefined : json['contentTypeId'],
        'sizeBytes': json['sizeBytes'] == null ? undefined : json['sizeBytes'],
        'plainSHA256Hash': json['plainSHA256Hash'] == null ? undefined : json['plainSHA256Hash'],
        'createdStamp': json['createdStamp'] == null ? undefined : (new Date(json['createdStamp'])),
        'beginStamp': json['beginStamp'] == null ? undefined : (new Date(json['beginStamp'])),
        'endStamp': json['endStamp'] == null ? undefined : (new Date(json['endStamp'])),
    };
}

export function FileCreateRequestDTOToJSON(json: any): FileCreateRequestDTO {
    return FileCreateRequestDTOToJSONTyped(json, false);
}

export function FileCreateRequestDTOToJSONTyped(value?: FileCreateRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'contentTypeId': value['contentTypeId'],
        'sizeBytes': value['sizeBytes'],
        'plainSHA256Hash': value['plainSHA256Hash'],
        'createdStamp': value['createdStamp'] == null ? value['createdStamp'] : value['createdStamp'].toISOString(),
        'beginStamp': value['beginStamp'] == null ? value['beginStamp'] : value['beginStamp'].toISOString(),
        'endStamp': value['endStamp'] == null ? value['endStamp'] : value['endStamp'].toISOString(),
    };
}

