/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileCreateRequestDTO
 */
export interface FileCreateRequestDTO {
    /**
     * 
     * @type {string}
     * @memberof FileCreateRequestDTO
     */
    name?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileCreateRequestDTO
     */
    contentTypeId?: string | null;
    /**
     * 
     * @type {string}
     * @memberof FileCreateRequestDTO
     */
    associatedDataSetId?: string | null;
    /**
     * 
     * @type {number}
     * @memberof FileCreateRequestDTO
     */
    size?: number | null;
    /**
     * 
     * @type {string}
     * @memberof FileCreateRequestDTO
     */
    hash?: string | null;
    /**
     * 
     * @type {Date}
     * @memberof FileCreateRequestDTO
     */
    createdStamp?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FileCreateRequestDTO
     */
    beginStamp?: Date | null;
    /**
     * 
     * @type {Date}
     * @memberof FileCreateRequestDTO
     */
    endStamp?: Date | null;
}

/**
 * Check if a given object implements the FileCreateRequestDTO interface.
 */
export function instanceOfFileCreateRequestDTO(value: object): value is FileCreateRequestDTO {
    return true;
}

export function FileCreateRequestDTOFromJSON(json: any): FileCreateRequestDTO {
    return FileCreateRequestDTOFromJSONTyped(json, false);
}

export function FileCreateRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileCreateRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'contentTypeId': json['contentTypeId'] == null ? undefined : json['contentTypeId'],
        'associatedDataSetId': json['associatedDataSetId'] == null ? undefined : json['associatedDataSetId'],
        'size': json['size'] == null ? undefined : json['size'],
        'hash': json['hash'] == null ? undefined : json['hash'],
        'createdStamp': json['createdStamp'] == null ? undefined : (new Date(json['createdStamp'])),
        'beginStamp': json['beginStamp'] == null ? undefined : (new Date(json['beginStamp'])),
        'endStamp': json['endStamp'] == null ? undefined : (new Date(json['endStamp'])),
    };
}

export function FileCreateRequestDTOToJSON(value?: FileCreateRequestDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'name': value['name'],
        'contentTypeId': value['contentTypeId'],
        'associatedDataSetId': value['associatedDataSetId'],
        'size': value['size'],
        'hash': value['hash'],
        'createdStamp': value['createdStamp'] == null ? undefined : ((value['createdStamp'] as any).toISOString()),
        'beginStamp': value['beginStamp'] == null ? undefined : ((value['beginStamp'] as any).toISOString()),
        'endStamp': value['endStamp'] == null ? undefined : ((value['endStamp'] as any).toISOString()),
    };
}

