/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const JobState = {
    Created: 'Created',
    Pending: 'Pending',
    Running: 'Running',
    Failed: 'Failed',
    Finished: 'Finished',
    Terminated: 'Terminated',
    RunnerNotResponding: 'RunnerNotResponding'
} as const;
export type JobState = typeof JobState[keyof typeof JobState];


export function instanceOfJobState(value: any): boolean {
    for (const key in JobState) {
        if (Object.prototype.hasOwnProperty.call(JobState, key)) {
            if (JobState[key as keyof typeof JobState] === value) {
                return true;
            }
        }
    }
    return false;
}

export function JobStateFromJSON(json: any): JobState {
    return JobStateFromJSONTyped(json, false);
}

export function JobStateFromJSONTyped(json: any, ignoreDiscriminator: boolean): JobState {
    return json as JobState;
}

export function JobStateToJSON(value?: JobState | null): any {
    return value as any;
}

export function JobStateToJSONTyped(value: any, ignoreDiscriminator: boolean): JobState {
    return value as JobState;
}

