/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SchemaDTO } from './SchemaDTO';
import {
    SchemaDTOFromJSON,
    SchemaDTOFromJSONTyped,
    SchemaDTOToJSON,
    SchemaDTOToJSONTyped,
} from './SchemaDTO';

/**
 * 
 * @export
 * @interface MetaDateCollectionColumnDTO
 */
export interface MetaDateCollectionColumnDTO {
    /**
     * 
     * @type {string}
     * @memberof MetaDateCollectionColumnDTO
     */
    metadataKey?: string | null;
    /**
     * 
     * @type {SchemaDTO}
     * @memberof MetaDateCollectionColumnDTO
     */
    schema?: SchemaDTO;
    /**
     * 
     * @type {string}
     * @memberof MetaDateCollectionColumnDTO
     */
    defaultFieldId?: string | null;
}

/**
 * Check if a given object implements the MetaDateCollectionColumnDTO interface.
 */
export function instanceOfMetaDateCollectionColumnDTO(value: object): value is MetaDateCollectionColumnDTO {
    return true;
}

export function MetaDateCollectionColumnDTOFromJSON(json: any): MetaDateCollectionColumnDTO {
    return MetaDateCollectionColumnDTOFromJSONTyped(json, false);
}

export function MetaDateCollectionColumnDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaDateCollectionColumnDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'metadataKey': json['metadataKey'] == null ? undefined : json['metadataKey'],
        'schema': json['schema'] == null ? undefined : SchemaDTOFromJSON(json['schema']),
        'defaultFieldId': json['defaultFieldId'] == null ? undefined : json['defaultFieldId'],
    };
}

export function MetaDateCollectionColumnDTOToJSON(json: any): MetaDateCollectionColumnDTO {
    return MetaDateCollectionColumnDTOToJSONTyped(json, false);
}

export function MetaDateCollectionColumnDTOToJSONTyped(value?: MetaDateCollectionColumnDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'metadataKey': value['metadataKey'],
        'schema': SchemaDTOToJSON(value['schema']),
        'defaultFieldId': value['defaultFieldId'],
    };
}

