/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SchemaDTO } from './SchemaDTO';
import {
    SchemaDTOFromJSON,
    SchemaDTOFromJSONTyped,
    SchemaDTOToJSON,
    SchemaDTOToJSONTyped,
} from './SchemaDTO';

/**
 * 
 * @export
 * @interface MetaDateDTO
 */
export interface MetaDateDTO {
    /**
     * The id of this meta date.
     * @type {string}
     * @memberof MetaDateDTO
     */
    id?: string | null;
    /**
     * List of schema ids that have been validated against this meta date.
     * @type {Array<SchemaDTO>}
     * @memberof MetaDateDTO
     */
    validatedSchemas?: Array<SchemaDTO> | null;
    /**
     * The id of the file representing the stored meta date. Retrieve content via Files API.
     * @type {string}
     * @memberof MetaDateDTO
     */
    fileId?: string | null;
}

/**
 * Check if a given object implements the MetaDateDTO interface.
 */
export function instanceOfMetaDateDTO(value: object): value is MetaDateDTO {
    return true;
}

export function MetaDateDTOFromJSON(json: any): MetaDateDTO {
    return MetaDateDTOFromJSONTyped(json, false);
}

export function MetaDateDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetaDateDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'validatedSchemas': json['validatedSchemas'] == null ? undefined : ((json['validatedSchemas'] as Array<any>).map(SchemaDTOFromJSON)),
        'fileId': json['fileId'] == null ? undefined : json['fileId'],
    };
}

export function MetaDateDTOToJSON(json: any): MetaDateDTO {
    return MetaDateDTOToJSONTyped(json, false);
}

export function MetaDateDTOToJSONTyped(value?: MetaDateDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'validatedSchemas': value['validatedSchemas'] == null ? undefined : ((value['validatedSchemas'] as Array<any>).map(SchemaDTOToJSON)),
        'fileId': value['fileId'],
    };
}

