/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const MetadataColumnTargetDTO = {
    Dataset: 'Dataset',
    File: 'File'
} as const;
export type MetadataColumnTargetDTO = typeof MetadataColumnTargetDTO[keyof typeof MetadataColumnTargetDTO];


export function instanceOfMetadataColumnTargetDTO(value: any): boolean {
    for (const key in MetadataColumnTargetDTO) {
        if (Object.prototype.hasOwnProperty.call(MetadataColumnTargetDTO, key)) {
            if (MetadataColumnTargetDTO[key as keyof typeof MetadataColumnTargetDTO] === value) {
                return true;
            }
        }
    }
    return false;
}

export function MetadataColumnTargetDTOFromJSON(json: any): MetadataColumnTargetDTO {
    return MetadataColumnTargetDTOFromJSONTyped(json, false);
}

export function MetadataColumnTargetDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): MetadataColumnTargetDTO {
    return json as MetadataColumnTargetDTO;
}

export function MetadataColumnTargetDTOToJSON(value?: MetadataColumnTargetDTO | null): any {
    return value as any;
}

export function MetadataColumnTargetDTOToJSONTyped(value: any, ignoreDiscriminator: boolean): MetadataColumnTargetDTO {
    return value as MetadataColumnTargetDTO;
}

