/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { DataStoreSummaryDTO } from './DataStoreSummaryDTO';
import {
    DataStoreSummaryDTOFromJSON,
    DataStoreSummaryDTOFromJSONTyped,
    DataStoreSummaryDTOToJSON,
} from './DataStoreSummaryDTO';
import type { CollectionSummaryDTO } from './CollectionSummaryDTO';
import {
    CollectionSummaryDTOFromJSON,
    CollectionSummaryDTOFromJSONTyped,
    CollectionSummaryDTOToJSON,
} from './CollectionSummaryDTO';

/**
 * 
 * @export
 * @interface ProjectSummaryDTO
 */
export interface ProjectSummaryDTO {
    /**
     * The id of this project.
     * @type {string}
     * @memberof ProjectSummaryDTO
     */
    id?: string | null;
    /**
     * The name of this project.
     * @type {string}
     * @memberof ProjectSummaryDTO
     */
    name?: string | null;
    /**
     * The slug of this project.
     * @type {string}
     * @memberof ProjectSummaryDTO
     */
    slug?: string | null;
    /**
     * All collections assigned to this project.
     * @type {Array<CollectionSummaryDTO>}
     * @memberof ProjectSummaryDTO
     */
    collections?: Array<CollectionSummaryDTO> | null;
    /**
     * All data stores assigned to this project.
     * @type {Array<DataStoreSummaryDTO>}
     * @memberof ProjectSummaryDTO
     */
    dataStores?: Array<DataStoreSummaryDTO> | null;
}

/**
 * Check if a given object implements the ProjectSummaryDTO interface.
 */
export function instanceOfProjectSummaryDTO(value: object): value is ProjectSummaryDTO {
    return true;
}

export function ProjectSummaryDTOFromJSON(json: any): ProjectSummaryDTO {
    return ProjectSummaryDTOFromJSONTyped(json, false);
}

export function ProjectSummaryDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ProjectSummaryDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
        'slug': json['slug'] == null ? undefined : json['slug'],
        'collections': json['collections'] == null ? undefined : ((json['collections'] as Array<any>).map(CollectionSummaryDTOFromJSON)),
        'dataStores': json['dataStores'] == null ? undefined : ((json['dataStores'] as Array<any>).map(DataStoreSummaryDTOFromJSON)),
    };
}

export function ProjectSummaryDTOToJSON(value?: ProjectSummaryDTO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'id': value['id'],
        'name': value['name'],
        'slug': value['slug'],
        'collections': value['collections'] == null ? undefined : ((value['collections'] as Array<any>).map(CollectionSummaryDTOToJSON)),
        'dataStores': value['dataStores'] == null ? undefined : ((value['dataStores'] as Array<any>).map(DataStoreSummaryDTOToJSON)),
    };
}

