/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const QueryMode = {
    And: 'And',
    Or: 'Or'
} as const;
export type QueryMode = typeof QueryMode[keyof typeof QueryMode];


export function instanceOfQueryMode(value: any): boolean {
    for (const key in QueryMode) {
        if (Object.prototype.hasOwnProperty.call(QueryMode, key)) {
            if (QueryMode[key as keyof typeof QueryMode] === value) {
                return true;
            }
        }
    }
    return false;
}

export function QueryModeFromJSON(json: any): QueryMode {
    return QueryModeFromJSONTyped(json, false);
}

export function QueryModeFromJSONTyped(json: any, ignoreDiscriminator: boolean): QueryMode {
    return json as QueryMode;
}

export function QueryModeToJSON(value?: QueryMode | null): any {
    return value as any;
}

export function QueryModeToJSONTyped(value: any, ignoreDiscriminator: boolean): QueryMode {
    return value as QueryMode;
}

