/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SealedS3DataSetFileCreateRequestDTO } from './SealedS3DataSetFileCreateRequestDTO';
import {
    SealedS3DataSetFileCreateRequestDTOFromJSON,
    SealedS3DataSetFileCreateRequestDTOFromJSONTyped,
    SealedS3DataSetFileCreateRequestDTOToJSON,
    SealedS3DataSetFileCreateRequestDTOToJSONTyped,
} from './SealedS3DataSetFileCreateRequestDTO';

/**
 * Request body for registering an already existing S3-backed dataset and sealing it in one operation.
 * Object keys are relative to the referenced RDPMS.Core.Persistence.Model.S3DataStore.KeyPrefix.
 * @export
 * @interface SealedS3DataSetCreateRequestDTO
 */
export interface SealedS3DataSetCreateRequestDTO {
    /**
     * Optional human-readable identifier. Must be unique within the collection.
     * @type {string}
     * @memberof SealedS3DataSetCreateRequestDTO
     */
    slug?: string | null;
    /**
     * Mandatory dataset name.
     * @type {string}
     * @memberof SealedS3DataSetCreateRequestDTO
     */
    name?: string | null;
    /**
     * Mandatory creation timestamp in UTC.
     * @type {Date}
     * @memberof SealedS3DataSetCreateRequestDTO
     */
    createdStampUTC?: Date | null;
    /**
     * Mandatory parent collection id.
     * @type {string}
     * @memberof SealedS3DataSetCreateRequestDTO
     */
    collectionId?: string | null;
    /**
     * Mandatory S3 datastore id. Its endpoint, bucket, and key prefix are used to validate all file references.
     * @type {string}
     * @memberof SealedS3DataSetCreateRequestDTO
     */
    storeId?: string | null;
    /**
     * Files to register as part of this dataset.
     * @type {Array<SealedS3DataSetFileCreateRequestDTO>}
     * @memberof SealedS3DataSetCreateRequestDTO
     */
    files?: Array<SealedS3DataSetFileCreateRequestDTO> | null;
}

/**
 * Check if a given object implements the SealedS3DataSetCreateRequestDTO interface.
 */
export function instanceOfSealedS3DataSetCreateRequestDTO(value: object): value is SealedS3DataSetCreateRequestDTO {
    return true;
}

export function SealedS3DataSetCreateRequestDTOFromJSON(json: any): SealedS3DataSetCreateRequestDTO {
    return SealedS3DataSetCreateRequestDTOFromJSONTyped(json, false);
}

export function SealedS3DataSetCreateRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SealedS3DataSetCreateRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'slug': json['slug'] == null ? undefined : json['slug'],
        'name': json['name'] == null ? undefined : json['name'],
        'createdStampUTC': json['createdStampUTC'] == null ? undefined : (new Date(json['createdStampUTC'])),
        'collectionId': json['collectionId'] == null ? undefined : json['collectionId'],
        'storeId': json['storeId'] == null ? undefined : json['storeId'],
        'files': json['files'] == null ? undefined : ((json['files'] as Array<any>).map(SealedS3DataSetFileCreateRequestDTOFromJSON)),
    };
}

export function SealedS3DataSetCreateRequestDTOToJSON(json: any): SealedS3DataSetCreateRequestDTO {
    return SealedS3DataSetCreateRequestDTOToJSONTyped(json, false);
}

export function SealedS3DataSetCreateRequestDTOToJSONTyped(value?: SealedS3DataSetCreateRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'slug': value['slug'],
        'name': value['name'],
        'createdStampUTC': value['createdStampUTC'] == null ? value['createdStampUTC'] : value['createdStampUTC'].toISOString(),
        'collectionId': value['collectionId'],
        'storeId': value['storeId'],
        'files': value['files'] == null ? undefined : ((value['files'] as Array<any>).map(SealedS3DataSetFileCreateRequestDTOToJSON)),
    };
}

