/* tslint:disable */
/* eslint-disable */
/**
 * RDPMS API v1
 * RDPMS API v1
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * File entry for RDPMS.Core.Server.Model.DTO.V1.SealedS3DataSetCreateRequestDTO.
 * @export
 * @interface SealedS3DataSetFileCreateRequestDTO
 */
export interface SealedS3DataSetFileCreateRequestDTO {
    /**
     * File name as stored in RDPMS. This may include a relative path inside the dataset.
     * @type {string}
     * @memberof SealedS3DataSetFileCreateRequestDTO
     */
    name?: string | null;
    /**
     * S3 object key relative to the datastore prefix.
     * @type {string}
     * @memberof SealedS3DataSetFileCreateRequestDTO
     */
    objectKey?: string | null;
    /**
     * Content type id for this file.
     * @type {string}
     * @memberof SealedS3DataSetFileCreateRequestDTO
     */
    contentTypeId?: string | null;
    /**
     * Plain file size. For already existing S3 objects this is also used as the expected storage-reference size.
     * @type {number}
     * @memberof SealedS3DataSetFileCreateRequestDTO
     */
    sizeBytes?: number | null;
    /**
     * Optional SHA256 of the plain file. Unknown hashes may be omitted.
     * @type {string}
     * @memberof SealedS3DataSetFileCreateRequestDTO
     */
    plainSHA256Hash?: string | null;
    /**
     * Optional SHA256 of the stored object. Defaults to PlainSHA256Hash when omitted.
     * @type {string}
     * @memberof SealedS3DataSetFileCreateRequestDTO
     */
    storedSHA256Hash?: string | null;
    /**
     * Optional storage compression algorithm. Defaults to Plain.
     * @type {string}
     * @memberof SealedS3DataSetFileCreateRequestDTO
     */
    compressionAlgorithm?: string | null;
    /**
     * Optional file creation timestamp in UTC. Defaults to dataset CreatedStampUTC.
     * @type {Date}
     * @memberof SealedS3DataSetFileCreateRequestDTO
     */
    createdStampUTC?: Date | null;
    /**
     * Optional first timestamp represented by this file.
     * @type {Date}
     * @memberof SealedS3DataSetFileCreateRequestDTO
     */
    beginStampUTC?: Date | null;
    /**
     * Optional final timestamp represented by this file.
     * @type {Date}
     * @memberof SealedS3DataSetFileCreateRequestDTO
     */
    endStampUTC?: Date | null;
}

/**
 * Check if a given object implements the SealedS3DataSetFileCreateRequestDTO interface.
 */
export function instanceOfSealedS3DataSetFileCreateRequestDTO(value: object): value is SealedS3DataSetFileCreateRequestDTO {
    return true;
}

export function SealedS3DataSetFileCreateRequestDTOFromJSON(json: any): SealedS3DataSetFileCreateRequestDTO {
    return SealedS3DataSetFileCreateRequestDTOFromJSONTyped(json, false);
}

export function SealedS3DataSetFileCreateRequestDTOFromJSONTyped(json: any, ignoreDiscriminator: boolean): SealedS3DataSetFileCreateRequestDTO {
    if (json == null) {
        return json;
    }
    return {
        
        'name': json['name'] == null ? undefined : json['name'],
        'objectKey': json['objectKey'] == null ? undefined : json['objectKey'],
        'contentTypeId': json['contentTypeId'] == null ? undefined : json['contentTypeId'],
        'sizeBytes': json['sizeBytes'] == null ? undefined : json['sizeBytes'],
        'plainSHA256Hash': json['plainSHA256Hash'] == null ? undefined : json['plainSHA256Hash'],
        'storedSHA256Hash': json['storedSHA256Hash'] == null ? undefined : json['storedSHA256Hash'],
        'compressionAlgorithm': json['compressionAlgorithm'] == null ? undefined : json['compressionAlgorithm'],
        'createdStampUTC': json['createdStampUTC'] == null ? undefined : (new Date(json['createdStampUTC'])),
        'beginStampUTC': json['beginStampUTC'] == null ? undefined : (new Date(json['beginStampUTC'])),
        'endStampUTC': json['endStampUTC'] == null ? undefined : (new Date(json['endStampUTC'])),
    };
}

export function SealedS3DataSetFileCreateRequestDTOToJSON(json: any): SealedS3DataSetFileCreateRequestDTO {
    return SealedS3DataSetFileCreateRequestDTOToJSONTyped(json, false);
}

export function SealedS3DataSetFileCreateRequestDTOToJSONTyped(value?: SealedS3DataSetFileCreateRequestDTO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'name': value['name'],
        'objectKey': value['objectKey'],
        'contentTypeId': value['contentTypeId'],
        'sizeBytes': value['sizeBytes'],
        'plainSHA256Hash': value['plainSHA256Hash'],
        'storedSHA256Hash': value['storedSHA256Hash'],
        'compressionAlgorithm': value['compressionAlgorithm'],
        'createdStampUTC': value['createdStampUTC'] == null ? value['createdStampUTC'] : value['createdStampUTC'].toISOString(),
        'beginStampUTC': value['beginStampUTC'] == null ? value['beginStampUTC'] : value['beginStampUTC'].toISOString(),
        'endStampUTC': value['endStampUTC'] == null ? value['endStampUTC'] : value['endStampUTC'].toISOString(),
    };
}

