# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
import pprint
from pydantic import BaseModel, ConfigDict, Field, StrictStr, ValidationError, field_validator
from typing import Any, List, Optional
from rdpms_cli.openapi_client.models.file_detailed_dto import FileDetailedDTO
from rdpms_cli.openapi_client.models.file_metadata_summary_dto import FileMetadataSummaryDTO
from rdpms_cli.openapi_client.models.file_summary_dto import FileSummaryDTO
from pydantic import StrictStr, Field
from typing import Union, List, Set, Optional, Dict
from typing_extensions import Literal, Self

APIV1DATAFILESGET200RESPONSEINNER_ONE_OF_SCHEMAS = ["FileDetailedDTO", "FileMetadataSummaryDTO", "FileSummaryDTO"]

class ApiV1DataFilesGet200ResponseInner(BaseModel):
    """
    ApiV1DataFilesGet200ResponseInner
    """
    # data type: FileSummaryDTO
    oneof_schema_1_validator: Optional[FileSummaryDTO] = None
    # data type: FileMetadataSummaryDTO
    oneof_schema_2_validator: Optional[FileMetadataSummaryDTO] = None
    # data type: FileDetailedDTO
    oneof_schema_3_validator: Optional[FileDetailedDTO] = None
    actual_instance: Optional[Union[FileDetailedDTO, FileMetadataSummaryDTO, FileSummaryDTO]] = None
    one_of_schemas: Set[str] = { "FileDetailedDTO", "FileMetadataSummaryDTO", "FileSummaryDTO" }

    model_config = ConfigDict(
        validate_assignment=True,
        protected_namespaces=(),
    )


    discriminator_value_class_map: Dict[str, str] = {
    }

    def __init__(self, *args, **kwargs) -> None:
        if args:
            if len(args) > 1:
                raise ValueError("If a position argument is used, only 1 is allowed to set `actual_instance`")
            if kwargs:
                raise ValueError("If a position argument is used, keyword arguments cannot be used.")
            super().__init__(actual_instance=args[0])
        else:
            super().__init__(**kwargs)

    @field_validator('actual_instance')
    def actual_instance_must_validate_oneof(cls, v):
        instance = ApiV1DataFilesGet200ResponseInner.model_construct()
        error_messages = []
        match = 0
        # validate data type: FileSummaryDTO
        if not isinstance(v, FileSummaryDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FileSummaryDTO`")
        else:
            match += 1
        # validate data type: FileMetadataSummaryDTO
        if not isinstance(v, FileMetadataSummaryDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FileMetadataSummaryDTO`")
        else:
            match += 1
        # validate data type: FileDetailedDTO
        if not isinstance(v, FileDetailedDTO):
            error_messages.append(f"Error! Input type `{type(v)}` is not `FileDetailedDTO`")
        else:
            match += 1
        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when setting `actual_instance` in ApiV1DataFilesGet200ResponseInner with oneOf schemas: FileDetailedDTO, FileMetadataSummaryDTO, FileSummaryDTO. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when setting `actual_instance` in ApiV1DataFilesGet200ResponseInner with oneOf schemas: FileDetailedDTO, FileMetadataSummaryDTO, FileSummaryDTO. Details: " + ", ".join(error_messages))
        else:
            return v

    @classmethod
    def from_dict(cls, obj: Union[str, Dict[str, Any]]) -> Self:
        return cls.from_json(json.dumps(obj))

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Returns the object represented by the json string"""
        instance = cls.model_construct()
        error_messages = []
        match = 0

        # deserialize data into FileSummaryDTO
        try:
            instance.actual_instance = FileSummaryDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FileMetadataSummaryDTO
        try:
            instance.actual_instance = FileMetadataSummaryDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))
        # deserialize data into FileDetailedDTO
        try:
            instance.actual_instance = FileDetailedDTO.from_json(json_str)
            match += 1
        except (ValidationError, ValueError) as e:
            error_messages.append(str(e))

        if match > 1:
            # more than 1 match
            raise ValueError("Multiple matches found when deserializing the JSON string into ApiV1DataFilesGet200ResponseInner with oneOf schemas: FileDetailedDTO, FileMetadataSummaryDTO, FileSummaryDTO. Details: " + ", ".join(error_messages))
        elif match == 0:
            # no match
            raise ValueError("No match found when deserializing the JSON string into ApiV1DataFilesGet200ResponseInner with oneOf schemas: FileDetailedDTO, FileMetadataSummaryDTO, FileSummaryDTO. Details: " + ", ".join(error_messages))
        else:
            return instance

    def to_json(self) -> str:
        """Returns the JSON representation of the actual instance"""
        if self.actual_instance is None:
            return "null"

        if hasattr(self.actual_instance, "to_json") and callable(self.actual_instance.to_json):
            return self.actual_instance.to_json()
        else:
            return json.dumps(self.actual_instance)

    def to_dict(self) -> Optional[Union[Dict[str, Any], FileDetailedDTO, FileMetadataSummaryDTO, FileSummaryDTO]]:
        """Returns the dict representation of the actual instance"""
        if self.actual_instance is None:
            return None

        if hasattr(self.actual_instance, "to_dict") and callable(self.actual_instance.to_dict):
            return self.actual_instance.to_dict()
        else:
            # primitive type
            return self.actual_instance

    def to_str(self) -> str:
        """Returns the string representation of the actual instance"""
        return pprint.pformat(self.model_dump())


