# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from rdpms_cli.openapi_client.models.meta_date_dto import MetaDateDTO
from typing import Optional, Set
from typing_extensions import Self

class AssignedMetaDateDTO(BaseModel):
    """
    AssignedMetaDateDTO
    """ # noqa: E501
    metadata_key: Optional[StrictStr] = Field(default=None, description="Key linking an entity to a meta date.", alias="metadataKey")
    metadata_id: Optional[UUID] = Field(default=None, description="Id of the meta date.", alias="metadataId")
    var_field: Optional[MetaDateDTO] = Field(default=None, alias="field")
    inherited: Optional[StrictBool] = Field(default=None, description="Whether this meta date is inherited from the parent collection.")
    collection_schema_verified: Optional[StrictBool] = Field(default=None, description="Whether the schema, the collection declares for this key, has been verified.", alias="collectionSchemaVerified")
    __properties: ClassVar[List[str]] = ["metadataKey", "metadataId", "field", "inherited", "collectionSchemaVerified"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of AssignedMetaDateDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of var_field
        if self.var_field:
            _dict['field'] = self.var_field.to_dict()
        # set to None if metadata_key (nullable) is None
        # and model_fields_set contains the field
        if self.metadata_key is None and "metadata_key" in self.model_fields_set:
            _dict['metadataKey'] = None

        # set to None if metadata_id (nullable) is None
        # and model_fields_set contains the field
        if self.metadata_id is None and "metadata_id" in self.model_fields_set:
            _dict['metadataId'] = None

        # set to None if inherited (nullable) is None
        # and model_fields_set contains the field
        if self.inherited is None and "inherited" in self.model_fields_set:
            _dict['inherited'] = None

        # set to None if collection_schema_verified (nullable) is None
        # and model_fields_set contains the field
        if self.collection_schema_verified is None and "collection_schema_verified" in self.model_fields_set:
            _dict['collectionSchemaVerified'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of AssignedMetaDateDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "metadataKey": obj.get("metadataKey"),
            "metadataId": obj.get("metadataId"),
            "field": MetaDateDTO.from_dict(obj["field"]) if obj.get("field") is not None else None,
            "inherited": obj.get("inherited"),
            "collectionSchemaVerified": obj.get("collectionSchemaVerified")
        })
        return _obj


