# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from rdpms_cli.openapi_client.models.job_state import JobState
from typing import Optional, Set
from typing_extensions import Self

class ExecutionSummaryDTO(BaseModel):
    """
    ExecutionSummaryDTO
    """ # noqa: E501
    id: Optional[UUID] = None
    name: Optional[StrictStr] = None
    pipeline_key: Optional[StrictStr] = Field(default=None, alias="pipelineKey")
    tracker_id: Optional[StrictStr] = Field(default=None, alias="trackerId")
    state: Optional[JobState] = None
    created_stamp_utc: Optional[datetime] = Field(default=None, alias="createdStampUtc")
    started_stamp_utc: Optional[datetime] = Field(default=None, alias="startedStampUtc")
    terminated_stamp_utc: Optional[datetime] = Field(default=None, alias="terminatedStampUtc")
    source_dataset_ids: Optional[List[UUID]] = Field(default=None, alias="sourceDatasetIds")
    output_dataset_ids: Optional[List[UUID]] = Field(default=None, alias="outputDatasetIds")
    metadata_ids: Optional[List[UUID]] = Field(default=None, alias="metadataIds")
    __properties: ClassVar[List[str]] = ["id", "name", "pipelineKey", "trackerId", "state", "createdStampUtc", "startedStampUtc", "terminatedStampUtc", "sourceDatasetIds", "outputDatasetIds", "metadataIds"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ExecutionSummaryDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if pipeline_key (nullable) is None
        # and model_fields_set contains the field
        if self.pipeline_key is None and "pipeline_key" in self.model_fields_set:
            _dict['pipelineKey'] = None

        # set to None if tracker_id (nullable) is None
        # and model_fields_set contains the field
        if self.tracker_id is None and "tracker_id" in self.model_fields_set:
            _dict['trackerId'] = None

        # set to None if started_stamp_utc (nullable) is None
        # and model_fields_set contains the field
        if self.started_stamp_utc is None and "started_stamp_utc" in self.model_fields_set:
            _dict['startedStampUtc'] = None

        # set to None if terminated_stamp_utc (nullable) is None
        # and model_fields_set contains the field
        if self.terminated_stamp_utc is None and "terminated_stamp_utc" in self.model_fields_set:
            _dict['terminatedStampUtc'] = None

        # set to None if source_dataset_ids (nullable) is None
        # and model_fields_set contains the field
        if self.source_dataset_ids is None and "source_dataset_ids" in self.model_fields_set:
            _dict['sourceDatasetIds'] = None

        # set to None if output_dataset_ids (nullable) is None
        # and model_fields_set contains the field
        if self.output_dataset_ids is None and "output_dataset_ids" in self.model_fields_set:
            _dict['outputDatasetIds'] = None

        # set to None if metadata_ids (nullable) is None
        # and model_fields_set contains the field
        if self.metadata_ids is None and "metadata_ids" in self.model_fields_set:
            _dict['metadataIds'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ExecutionSummaryDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "pipelineKey": obj.get("pipelineKey"),
            "trackerId": obj.get("trackerId"),
            "state": obj.get("state"),
            "createdStampUtc": obj.get("createdStampUtc"),
            "startedStampUtc": obj.get("startedStampUtc"),
            "terminatedStampUtc": obj.get("terminatedStampUtc"),
            "sourceDatasetIds": obj.get("sourceDatasetIds"),
            "outputDatasetIds": obj.get("outputDatasetIds"),
            "metadataIds": obj.get("metadataIds")
        })
        return _obj


