# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from rdpms_cli.openapi_client.models.content_type_dto import ContentTypeDTO
from typing import Optional, Set
from typing_extensions import Self

class FileSummaryDTO(BaseModel):
    """
    FileSummaryDTO
    """ # noqa: E501
    id: Optional[StrictStr] = None
    name: Optional[StrictStr] = None
    download_uri: Optional[StrictStr] = Field(default=None, alias="downloadURI")
    content_type: Optional[ContentTypeDTO] = Field(default=None, alias="contentType")
    size: Optional[StrictInt] = None
    created_stamp_utc: Optional[datetime] = Field(default=None, alias="createdStampUTC")
    deleted_stamp_utc: Optional[datetime] = Field(default=None, alias="deletedStampUTC")
    begin_stamp_utc: Optional[datetime] = Field(default=None, alias="beginStampUTC")
    end_stamp_utc: Optional[datetime] = Field(default=None, alias="endStampUTC")
    is_time_series: Optional[StrictBool] = Field(default=None, alias="isTimeSeries")
    is_deleted: Optional[StrictBool] = Field(default=None, alias="isDeleted")
    __properties: ClassVar[List[str]] = ["id", "name", "downloadURI", "contentType", "size", "createdStampUTC", "deletedStampUTC", "beginStampUTC", "endStampUTC", "isTimeSeries", "isDeleted"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileSummaryDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of content_type
        if self.content_type:
            _dict['contentType'] = self.content_type.to_dict()
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if download_uri (nullable) is None
        # and model_fields_set contains the field
        if self.download_uri is None and "download_uri" in self.model_fields_set:
            _dict['downloadURI'] = None

        # set to None if size (nullable) is None
        # and model_fields_set contains the field
        if self.size is None and "size" in self.model_fields_set:
            _dict['size'] = None

        # set to None if created_stamp_utc (nullable) is None
        # and model_fields_set contains the field
        if self.created_stamp_utc is None and "created_stamp_utc" in self.model_fields_set:
            _dict['createdStampUTC'] = None

        # set to None if deleted_stamp_utc (nullable) is None
        # and model_fields_set contains the field
        if self.deleted_stamp_utc is None and "deleted_stamp_utc" in self.model_fields_set:
            _dict['deletedStampUTC'] = None

        # set to None if begin_stamp_utc (nullable) is None
        # and model_fields_set contains the field
        if self.begin_stamp_utc is None and "begin_stamp_utc" in self.model_fields_set:
            _dict['beginStampUTC'] = None

        # set to None if end_stamp_utc (nullable) is None
        # and model_fields_set contains the field
        if self.end_stamp_utc is None and "end_stamp_utc" in self.model_fields_set:
            _dict['endStampUTC'] = None

        # set to None if is_time_series (nullable) is None
        # and model_fields_set contains the field
        if self.is_time_series is None and "is_time_series" in self.model_fields_set:
            _dict['isTimeSeries'] = None

        # set to None if is_deleted (nullable) is None
        # and model_fields_set contains the field
        if self.is_deleted is None and "is_deleted" in self.model_fields_set:
            _dict['isDeleted'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileSummaryDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "name": obj.get("name"),
            "downloadURI": obj.get("downloadURI"),
            "contentType": ContentTypeDTO.from_dict(obj["contentType"]) if obj.get("contentType") is not None else None,
            "size": obj.get("size"),
            "createdStampUTC": obj.get("createdStampUTC"),
            "deletedStampUTC": obj.get("deletedStampUTC"),
            "beginStampUTC": obj.get("beginStampUTC"),
            "endStampUTC": obj.get("endStampUTC"),
            "isTimeSeries": obj.get("isTimeSeries"),
            "isDeleted": obj.get("isDeleted")
        })
        return _obj


