# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class FileListViewMode(str, Enum):
    """
    FileListViewMode
    """

    """
    allowed enum values
    """
    SUMMARY = 'Summary'
    METADATA = 'Metadata'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of FileListViewMode from a JSON string"""
        return cls(json.loads(json_str))


