# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from typing import Optional, Set
from typing_extensions import Self

class FileStorageReferenceSummaryDTO(BaseModel):
    """
    FileStorageReferenceSummaryDTO
    """ # noqa: E501
    id: Optional[UUID] = None
    compression_algorithm: Optional[StrictStr] = Field(default=None, alias="compressionAlgorithm")
    size_bytes: Optional[StrictInt] = Field(default=None, alias="sizeBytes")
    sh_a256_hash: Optional[StrictStr] = Field(default=None, alias="shA256Hash")
    storage_type: Optional[StrictStr] = Field(default=None, alias="storageType")
    __properties: ClassVar[List[str]] = ["id", "compressionAlgorithm", "sizeBytes", "shA256Hash", "storageType"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of FileStorageReferenceSummaryDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if compression_algorithm (nullable) is None
        # and model_fields_set contains the field
        if self.compression_algorithm is None and "compression_algorithm" in self.model_fields_set:
            _dict['compressionAlgorithm'] = None

        # set to None if size_bytes (nullable) is None
        # and model_fields_set contains the field
        if self.size_bytes is None and "size_bytes" in self.model_fields_set:
            _dict['sizeBytes'] = None

        # set to None if sh_a256_hash (nullable) is None
        # and model_fields_set contains the field
        if self.sh_a256_hash is None and "sh_a256_hash" in self.model_fields_set:
            _dict['shA256Hash'] = None

        # set to None if storage_type (nullable) is None
        # and model_fields_set contains the field
        if self.storage_type is None and "storage_type" in self.model_fields_set:
            _dict['storageType'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of FileStorageReferenceSummaryDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "compressionAlgorithm": obj.get("compressionAlgorithm"),
            "sizeBytes": obj.get("sizeBytes"),
            "shA256Hash": obj.get("shA256Hash"),
            "storageType": obj.get("storageType")
        })
        return _obj


