# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from rdpms_cli.openapi_client.models.schema_dto import SchemaDTO
from typing import Optional, Set
from typing_extensions import Self

class MetaDateDTO(BaseModel):
    """
    MetaDateDTO
    """ # noqa: E501
    id: Optional[UUID] = Field(default=None, description="The id of this meta date.")
    validated_schemas: Optional[List[SchemaDTO]] = Field(default=None, description="List of schema ids that have been validated against this meta date.", alias="validatedSchemas")
    file_id: Optional[UUID] = Field(default=None, description="The id of the file representing the stored meta date. Retrieve content via Files API.", alias="fileId")
    __properties: ClassVar[List[str]] = ["id", "validatedSchemas", "fileId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of MetaDateDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in validated_schemas (list)
        _items = []
        if self.validated_schemas:
            for _item_validated_schemas in self.validated_schemas:
                if _item_validated_schemas:
                    _items.append(_item_validated_schemas.to_dict())
            _dict['validatedSchemas'] = _items
        # set to None if id (nullable) is None
        # and model_fields_set contains the field
        if self.id is None and "id" in self.model_fields_set:
            _dict['id'] = None

        # set to None if validated_schemas (nullable) is None
        # and model_fields_set contains the field
        if self.validated_schemas is None and "validated_schemas" in self.model_fields_set:
            _dict['validatedSchemas'] = None

        # set to None if file_id (nullable) is None
        # and model_fields_set contains the field
        if self.file_id is None and "file_id" in self.model_fields_set:
            _dict['fileId'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of MetaDateDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "validatedSchemas": [SchemaDTO.from_dict(_item) for _item in obj["validatedSchemas"]] if obj.get("validatedSchemas") is not None else None,
            "fileId": obj.get("fileId")
        })
        return _obj


