# coding: utf-8

"""
    RDPMS API v1

    RDPMS API v1

    The version of the OpenAPI document: v1
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from uuid import UUID
from rdpms_cli.openapi_client.models.sealed_s3_data_set_file_create_request_dto import SealedS3DataSetFileCreateRequestDTO
from typing import Optional, Set
from typing_extensions import Self

class SealedS3DataSetCreateRequestDTO(BaseModel):
    """
    Request body for registering an already existing S3-backed dataset and sealing it in one operation. Object keys are relative to the referenced RDPMS.Core.Persistence.Model.S3DataStore.KeyPrefix.
    """ # noqa: E501
    slug: Optional[StrictStr] = Field(default=None, description="Optional human-readable identifier. Must be unique within the collection.")
    name: Optional[StrictStr] = Field(default=None, description="Mandatory dataset name.")
    created_stamp_utc: Optional[datetime] = Field(default=None, description="Mandatory creation timestamp in UTC.", alias="createdStampUTC")
    collection_id: Optional[UUID] = Field(default=None, description="Mandatory parent collection id.", alias="collectionId")
    store_id: Optional[UUID] = Field(default=None, description="Mandatory S3 datastore id. Its endpoint, bucket, and key prefix are used to validate all file references.", alias="storeId")
    files: Optional[List[SealedS3DataSetFileCreateRequestDTO]] = Field(default=None, description="Files to register as part of this dataset.")
    __properties: ClassVar[List[str]] = ["slug", "name", "createdStampUTC", "collectionId", "storeId", "files"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of SealedS3DataSetCreateRequestDTO from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in files (list)
        _items = []
        if self.files:
            for _item_files in self.files:
                if _item_files:
                    _items.append(_item_files.to_dict())
            _dict['files'] = _items
        # set to None if slug (nullable) is None
        # and model_fields_set contains the field
        if self.slug is None and "slug" in self.model_fields_set:
            _dict['slug'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        # set to None if created_stamp_utc (nullable) is None
        # and model_fields_set contains the field
        if self.created_stamp_utc is None and "created_stamp_utc" in self.model_fields_set:
            _dict['createdStampUTC'] = None

        # set to None if collection_id (nullable) is None
        # and model_fields_set contains the field
        if self.collection_id is None and "collection_id" in self.model_fields_set:
            _dict['collectionId'] = None

        # set to None if store_id (nullable) is None
        # and model_fields_set contains the field
        if self.store_id is None and "store_id" in self.model_fields_set:
            _dict['storeId'] = None

        # set to None if files (nullable) is None
        # and model_fields_set contains the field
        if self.files is None and "files" in self.model_fields_set:
            _dict['files'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of SealedS3DataSetCreateRequestDTO from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "slug": obj.get("slug"),
            "name": obj.get("name"),
            "createdStampUTC": obj.get("createdStampUTC"),
            "collectionId": obj.get("collectionId"),
            "storeId": obj.get("storeId"),
            "files": [SealedS3DataSetFileCreateRequestDTO.from_dict(_item) for _item in obj["files"]] if obj.get("files") is not None else None
        })
        return _obj


